apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qiskit-functions
  namespace: argocd-prod
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
