[build-system]
requires = ["setuptools>=40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = ["ignore:::.*qiskit.opflow.*", "ignore:::.*qiskit.primitives.*"]
