# Generated by Django 4.1.6 on 2023-02-01 15:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NestedProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "dependencies",
                    models.JSONField(default=api.models.empty_list, null=True),
                ),
                (
                    "env_vars",
                    models.JSONField(default=api.models.empty_dict, null=True),
                ),
                (
                    "arguments",
                    models.JSONField(default=api.models.empty_dict, null=True),
                ),
                ("tags", models.JSONField(default=api.models.empty_list, null=True)),
                ("public", models.BooleanField(default=True)),
            ],
        ),
    ]
