# Generated by Django 4.2 on 2023-04-13 09:12

import api.models
import django.core.validators
from django.db import migrations, models
import django_prometheus.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("entrypoint", models.CharField(max_length=255)),
                ("working_dir", models.CharField(default="./", max_length=255)),
                ("version", models.CharField(default="0.0.0", max_length=100)),
                (
                    "dependencies",
                    models.JSONField(default=api.models.empty_list, null=True),
                ),
                (
                    "env_vars",
                    models.JSONField(default=api.models.empty_dict, null=True),
                ),
                (
                    "arguments",
                    models.JSONField(default=api.models.empty_dict, null=True),
                ),
                ("tags", models.JSONField(default=api.models.empty_list, null=True)),
                ("public", models.BooleanField(default=True)),
                (
                    "artifact",
                    models.FileField(
                        upload_to="artifacts_%Y_%m_%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["tar"]
                            )
                        ],
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("program"),
                models.Model,
            ),
        ),
    ]
