# Generated by Django 4.1.6 on 2023-02-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nestedprogram",
            name="entrypoint",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nestedprogram",
            name="version",
            field=models.CharField(default="0.0.0", max_length=100),
        ),
        migrations.AddField(
            model_name="nestedprogram",
            name="working_dir",
            field=models.CharField(default="./", max_length=255),
        ),
    ]
