# Generated by Django 4.1.6 on 2023-02-03 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_nestedprogram_entrypoint_nestedprogram_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nestedprogram",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
