# Generated by Django 4.1.7 on 2023-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_nestedprogram_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="nestedprogram",
            name="author",
            field=models.CharField(max_length=255, null="author"),
            preserve_default="author",
        ),
    ]
