# SPS configuration test 1

version: '1'

static-scan:
  skip: true

compliance-checks:
  skip: true

unit-tests:
  skip: true

containerize:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  dind: true
  abort_on_failure: false
  script: |
    #!/usr/bin/env bash
    source scripts/build_setup.sh
    source scripts/build.sh

deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0

dynamic-scan:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0

acceptance-test:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0

scan-artifact:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0

release:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0

finish:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0

test:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.40
  script: |
    #!/bin/sh
    exit 0


