FROM registry.access.redhat.com/ubi9-minimal:9.4@sha256:104cf11d890aeb7dd5728b7d7732e175a0e4018f1bb00d2faebcc8f6bf29bd52
RUN microdnf install -y \
    python3.11-3.11.9 \
    python3.11-devel-3.11.9 \
    vim-enhanced-8.2.2637 \
    wget-1.21.1 &&\
    microdnf clean all
RUN ln -s /usr/bin/python3.11 /usr/local/bin/python3 && \
    ln -s /usr/bin/python3.11 /usr/local/bin/python &&\
    ln -s /usr/bin/pip3.11 /usr/local/bin/pip3 &&\
    ln -s /usr/bin/pip3.11 /usr/local/bin/pip

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /
USER 0
RUN mkdir /data && chown 1000:1000 /data
RUN mkdir /function_data && chown 1000:1000 /function_data
COPY client ./qs
WORKDIR /qs

# Need versions of pip more recent than provided by UBI image
RUN python3.11 -m ensurepip --upgrade

RUN pip install --upgrade --no-cache-dir pip>=24.2

RUN pip install -r requirements.txt --no-cache-dir &&\
    pip install . --no-cache-dir &&\
    cp -r -n /usr/local/lib64/python3.11/site-packages/symengine /usr/local/lib/python3.11/site-packages &&\
    cp -r -n /usr/local/lib/python3.11/site-packages/symengine /usr/local/lib64/python3.11/site-packages

WORKDIR /
RUN rm -r ./qs

USER 1000
