ARG IMAGE_PY_VERSION=py39

FROM rayproject/ray:2.5.0-$IMAGE_PY_VERSION AS ray-node-amd64

WORKDIR /
USER 0
RUN mkdir /data && chown "$RAY_UID":"$RAY_UID" /data
USER $RAY_UID
COPY --chown=$RAY_UID:$RAY_UID ./client ./qs

WORKDIR /qs
# TODO: certifi version pinned to 2023.7.22. More info in #870
RUN pip install . --no-cache-dir &&\
    pip install --no-cache-dir certifi==2023.7.22

WORKDIR / 
RUN rm -r ./qs

FROM rayproject/ray:2.5.0-$IMAGE_PY_VERSION-aarch64 AS ray-node-arm64

WORKDIR /
USER 0
RUN mkdir /data && chown "$RAY_UID":"$RAY_UID" /data
USER $RAY_UID
RUN apt-get -y update &&\ 
    apt-get install --no-install-recommends -y \ 
    gcc=4:9.3.0-1ubuntu2 \ 
    build-essential=12.8ubuntu1
COPY --chown=$RAY_UID:$RAY_UID ./client ./qs

WORKDIR /qs
# TODO: scipy version pinned to 1.10, pyscf depends on. More info in #722
# TODO: certifi version pinned to 2023.7.22. More info in #870
RUN pip install . --no-cache-dir &&\
    if [ "$TARGETARCH" = "arm64" ] ; \
        then pip install --no-cache-dir pyscf==2.2.1 scipy==1.10 certifi==2023.7.22 ; \
    fi

WORKDIR /
USER 0
RUN rm -r ./qs
USER $RAY_UID

# hadolint ignore=DL3006
FROM ray-node-${TARGETARCH} AS final
