"""
This module handles the access to the logs store.
"""

import logging
from typing import Optional

from api.domain.exceptions.invalid_access_exception import InvalidAccessException
from core.models import Job
from core.services.storage import get_cos
from core.services.storage.enums.working_dir import WorkingDir
from core.services.storage.path_builder import PathBuilder

logger = logging.getLogger("core.LogsStorage")


class LogsStorage:
    """Manages access to logs generated by a Job via COS."""

    FILE_EXTENSION = ".log"
    PATH = "logs"

    def __init__(self, job: Job) -> None:
        self._job_id = str(job.id)
        self._username = job.author.username
        self._function_title = job.program.title
        self._provider_name = job.program.provider.name if job.program.provider else None
        self._cos = get_cos(job)

        self._public_key = PathBuilder.sub_path(
            working_dir=WorkingDir.USER_STORAGE,
            username=self._username,
            function_title=self._function_title,
            provider_name=self._provider_name,
            extra_sub_path=self.PATH,
        )

        if self._provider_name:
            self._private_key = PathBuilder.sub_path(
                working_dir=WorkingDir.PROVIDER_STORAGE,
                username=self._username,
                function_title=self._function_title,
                provider_name=self._provider_name,
                extra_sub_path=self.PATH,
            )
        else:
            self._private_key = None

    def _key(self, base_key: str) -> str:
        return f"{base_key}/{self._job_id}{self.FILE_EXTENSION}"

    def get_public_logs(self) -> Optional[str]:
        """Retrieve public logs for the job from COS."""
        return self._cos.get_object(self._key(self._public_key), WorkingDir.USER_STORAGE)

    def save_public_logs(self, logs: str) -> None:
        """Save public logs for the job to COS."""
        self._cos.put_object(self._key(self._public_key), logs, WorkingDir.USER_STORAGE)

    def get_private_logs(self) -> Optional[str]:
        """Retrieve private logs for the job from COS."""
        if self._private_key is None:
            raise RuntimeError("Private logs are only available for provider jobs")
        return self._cos.get_object(self._key(self._private_key), WorkingDir.PROVIDER_STORAGE)

    def save_private_logs(self, logs: str) -> None:
        """Save private logs for the job to COS."""
        if self._private_key is None:
            raise RuntimeError("Private logs are only available for provider jobs")
        self._cos.put_object(self._key(self._private_key), logs, WorkingDir.PROVIDER_STORAGE)
