"""
This module handles the access to the logs store.
"""

import logging
import os
from typing import Optional

from api.domain.exceptions.forbidden_error import ForbiddenError
from core.models import Job
from core.services.storage.enums.working_dir import WorkingDir
from core.services.storage.path_builder import PathBuilder

logger = logging.getLogger("gateway")


class LogsStorage:
    """
    Manages access to logs generated by a Job.

    Logs are stored in two locations:
    - Public logs belong to the user (USER_STORAGE)
    - Private logs belong to the provider (PROVIDER_STORAGE)
    """

    FILE_EXTENSION = ".log"
    PATH = "logs"
    ENCODING = "utf-8"

    def __init__(self, job: Job) -> None:
        self._job_id = str(job.id)
        self._username = job.author.username
        self._function_title = job.program.title
        self._provider_name = job.program.provider.name if job.program.provider else None

        # Build public logs path (USER_STORAGE)
        # User job: {author}/logs/
        # Provider job: {author}/{provider}/{function}/logs/
        self._public_path = PathBuilder.absolute_path(
            working_dir=WorkingDir.USER_STORAGE,
            username=self._username,
            function_title=self._function_title,
            provider_name=self._provider_name,
            extra_sub_path=self.PATH,
        )

        # Build private logs path (PROVIDER_STORAGE)
        # Path: {provider}/{function}/logs/
        if self._provider_name:
            self._private_path = PathBuilder.absolute_path(
                working_dir=WorkingDir.PROVIDER_STORAGE,
                username=self._username,
                function_title=self._function_title,
                provider_name=self._provider_name,
                extra_sub_path=self.PATH,
            )
        else:
            self._private_path = None

    def get_public_logs(self) -> Optional[str]:
        """Retrieve public logs for the job."""
        return self._read_logs(self._public_path)

    def save_public_logs(self, logs: str) -> None:
        """Save public logs for the job."""
        self._write_logs(self._public_path, logs)

    def get_private_logs(self) -> Optional[str]:
        """Retrieve private logs for the job (provider jobs only)."""
        if self._private_path is None:
            raise RuntimeError("Private logs are only available for provider jobs")
        return self._read_logs(self._private_path)

    def save_private_logs(self, logs: str) -> None:
        """Save private logs for the job (provider jobs only)."""
        if self._private_path is None:
            raise RuntimeError("Private logs are only available for provider jobs")
        self._write_logs(self._private_path, logs)

    def _get_file_path(self, base_path: str) -> str:
        """Return the full path to the log file."""
        return os.path.join(base_path, f"{self._job_id}{self.FILE_EXTENSION}")

    def _read_logs(self, base_path: str) -> Optional[str]:
        """Read logs from the given path."""
        log_path = self._get_file_path(base_path)
        if not os.path.exists(log_path):
            logger.info(
                "Log file for job ID '%s' not found at '%s'.",
                self._job_id,
                log_path,
            )
            return None

        try:
            with open(log_path, "r", encoding=self.ENCODING) as log_file:
                return log_file.read()
        except (UnicodeDecodeError, IOError) as e:
            logger.error(
                "Failed to read log file for job ID '%s': %s",
                self._job_id,
                str(e),
            )
            return None

    def _write_logs(self, base_path: str, logs: str) -> None:
        """Write logs to the given path."""
        log_path = self._get_file_path(base_path)
        try:
            with open(log_path, "w+", encoding=self.ENCODING) as log_file:
                log_file.write(logs)
        except (UnicodeDecodeError, IOError) as e:
            logger.error(
                "Failed to write log file for job ID '%s': %s",
                self._job_id,
                str(e),
            )
