[pytest]
DJANGO_SETTINGS_MODULE = main.settings
testpaths = tests
pythonpath = . ce-swagger-sdk
addopts =
    --verbose
    --tb=short
    -p no:warnings

console_output_style = count
minversion = 3.11

