site_name: 'Qiskit Serverless'
site_description: 'Qiskit Serverless'

repo_url: https://github.ibm.com/IBM-Q-Software/qiskit-serverless/
edit_uri: edit/master/techdocs/qiskit-serverless/docs/

nav:
  - index.md

plugins:
  - techdocs-core