# ===================
# Quantum Serverless configs
# ===================
platform: ibm

# ===================
# Ingress Nginx controller configs
# ===================

# Ingress Nginx controller is disabled by default to not affect cloud providers' controller configuration
nginxIngressControllerEnable: false
ingress:
  annotations:
    # For IBM Cloud the valid ingress class values are: public-iks-k8s-nginx and private-iks-k8s-nginx
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  tls:
    - hosts:
        - "gateway.middleware-prod-218f1d46487946bbe52597968f4638d3-0000.us-east.containers.appdomain.cloud"
      secretName: "middleware-prod-218f1d46487946bbe52597968f4638d3-0000"
  hosts:
    - host: "gateway.middleware-prod-218f1d46487946bbe52597968f4638d3-0000.us-east.containers.appdomain.cloud"
      paths:
      - path: /
        pathType: Prefix
        serviceName: "gateway"
        servicePort: 8000

# ===================
# Gateway configs
# ===================

gatewayEnable: true
gateway:
  nameOverride: "gateway"
  fullnameOverride: "gateway"
  useCertManager: false

  image:
    repository: "icr.io/quantum-public/quantum-serverless-gateway"
    pullPolicy: IfNotPresent
    tag: "0.7.0"
  application:
    siteHost: "http://gateway:8000"
    rayHost: "http://kuberay-head-svc:8265"
    auth:
      mechanism: "custom_token"
      token:
        url: "https://auth.quantum-computing.ibm.com/api/users/loginWithToken"
        verificationUrl: "https://auth.quantum-computing.ibm.com/api/users/me"
        verificationField: "ibmQNetwork;urls,services,serverless"
    superuser:
      enable: false
    service:
      type: ClusterIP
      port: 8000
    ray:
      nodeImage: "icr.io/quantum-public/quantum-serverless-ray-node:0.7.0-py39"
      opensslImage: registry.access.redhat.com/ubi8/openssl:8.8-7
      kubectlImage: alpine/k8s:1.28.1@sha256:c37a54b738e4d26f88d4a4d28680bb74dfea1d0e756f039dad900306abc837a8
      cpu: 4
      memory: 8
      replicas: 1
      minReplicas: 1
      maxReplicas: 2
    limits:
      maxJobsPerUser: 2
      maxComputeResources: 20

  cos:
    claimName: middleware-program

  secrets:
    secretKey:
      create: false
      name: gateway-secret-key
      key: GATEWAY_SECRET_KEY
    servicePsql:
      create: false
      name: binding-gateway-production-psql
      key:
        databaseName: connection.postgres.database
        databasePassword: connection.postgres.authentication.password
        host: connection.postgres.hosts.0.hostname
        port: connection.postgres.hosts.0.port
        userName: connection.postgres.authentication.username
    superuser:
      create: false

# ===================
# Jupyter configs
# ===================

jupyterEnable: false

# ===================
# Kuberay Operator
# ===================

kuberayOperatorEnable: true
kuberay-operator:
  image:
    repository: kuberay/operator
    tag: v0.6.0
    pullPolicy: IfNotPresent

# ===================
# Keycloak
# ===================

keycloakEnable: false

# ===================
# Quantum Repository
# ===================

repositoryEnable: false

# ===================
# COS
# ===================

cosEnable: false
