# ===================
# Qiskit Serverless Info
# ===================
global:
  version: 0.15.1

# ===================
# Qiskit Serverless configs
# ===================
platform: ibm

# ===================
# Ingress Nginx controller configs
# ===================

# Ingress Nginx controller is disabled by default to not affect cloud providers' controller configuration
nginxIngressControllerEnable: false

# ===================
# Gateway configs
# ===================

gatewayEnable: true
gateway:
  nameOverride: "gateway"
  fullnameOverride: "gateway"
  useCertManager: false

  image:
    repository: "icr.io/quantum-public/qiskit-serverless/gateway"
    pullPolicy: IfNotPresent
    tag: "0.15.1"
  resources:
    requests:
      memory: 2Gi
      cpu: 200m
    limits:
      memory: 4Gi
      cpu: 2000m
  application:
    siteHost: "http://gateway:8000"
    rayHost: "http://kuberay-head-svc:8265"
    auth:
      mechanism: "custom_token"
      token:
        url: "https://auth.quantum-computing.ibm.com/api/users/loginWithToken"
        verificationUrl: "https://auth.quantum-computing.ibm.com/api/users/me"
        verificationField: "ibmQNetwork;urls,services,serverless"
    superuser:
      enable: false
    service:
      type: ClusterIP
      port: 8000
    ray:
      nodeImage: "icr.io/quantum-public/qiskit-serverless/ray-node:0.15.1"
      opensslImage: registry.access.redhat.com/ubi8/openssl:8.8-9
      kubectlImage: alpine/k8s:1.28.9@sha256:4f97e78a640d569731ac71dccc27d7783b03488b383f15ca75ea975d31c3fe57
      proxyImage: "icr.io/quantum-public/qiskit-serverless/proxy:0.15.1"
      cpu: 12
      memory: 32
      replicas: 1
      minReplicas: 1
      maxReplicas: 1
      useTLS: false
    limits:
      maxJobsPerUser: 1
      maxComputeResources: 6
    proxy:
      enabled: false

  cos:
    claimName: qiskit-serverless-programs

  tasks:
    providersConfiguration: '{\"q-ctrl\":{\"admin_group\":[\"project-based/q-ctrl/main\"],\"registry\":\"icr.io\"},\"qunasys\":{\"admin_group\":[\"project-based/qunasys/main\"],\"registry\":\"icr.io\"},\"qedma\":{\"admin_group\":[\"project-based/qedma/main\"],\"registry\":\"icr.io\"},\"algorithmiq\":{\"admin_group\":[\"project-based/algorithmiq/main\"],\"registry\":\"icr.io\"},\"multiverse\":{\"admin_group\":[\"project-based/multiverse/main\"],\"registry\":\"icr.io\"}}'
    functionsPermissions: '{\"tem\":{\"provider\":\"algorithmiq\",\"instances\":[\"project-based/algorithmiq/main\"]},\"singularity\":{\"provider\":\"multiverse\",\"instances\":[\"project-based/multiverse/main\"]},\"performance-management\":{\"provider\":\"q-ctrl\",\"instances\":[\"project-based/q-ctrl/main\"]},\"optimization\":{\"provider\":\"q-ctrl\",\"instances\":[\"project-based/q-ctrl/main\"]},\"qce\":{\"provider\":\"qunasys\",\"instances\":[\"project-based/qunasys/main\"]},\"qsci\":{\"provider\":\"qunasys\",\"instances\":[\"project-based/qunasys/main\"]},\"qsci-vqe\":{\"provider\":\"qunasys\",\"instances\":[\"project-based/qunasys/main\"]},\"qesem\":{\"provider\":\"qedma\",\"instances\":[\"project-based/qedma/main\"]}}'

  secrets:
    secretKey:
      create: false
      name: gateway-production-secret-key
      key: payload
    servicePsql:
      create: false
      name: binding-qiskit-serverless-gateway-production-psql
      key:
        databaseName: connection.postgres.database
        databasePassword: connection.postgres.authentication.password
        host: connection.postgres.hosts.0.hostname
        port: connection.postgres.hosts.0.port
        userName: connection.postgres.authentication.username
    superuser:
      create: false

# ===================
# Kuberay Operator
# ===================

kuberayOperatorEnable: true
kuberay-operator:
  image:
    repository: kuberay/operator
    tag: v1.0.0
    pullPolicy: IfNotPresent

# ===================
# PostgreSQL
# ===================

postgresqlEnable: false

# ===================
# PVC
# ===================

createPvc: false

# ===================
# Istio
# ===================

istioEnable: true
istio:
  host: qiskit-serverless.quantum.ibm.com
  secretName: quantum-ibm-com
