# ===================
# Qiskit Serverless Info
# ===================
global:
  version: 0.11.0

# ===================
# Quantum Serverless configs
# ===================
platform: ibm

# ===================
# Ingress Nginx controller configs
# ===================

# Ingress Nginx controller is disabled by default to not affect cloud providers' controller configuration
nginxIngressControllerEnable: false

# ===================
# Gateway configs
# ===================

gatewayEnable: true
gateway:
  nameOverride: "gateway"
  fullnameOverride: "gateway"
  useCertManager: false

  image:
    repository: "icr.io/quantum-public/quantum-serverless-gateway"
    pullPolicy: IfNotPresent
    tag: "0.12.0"
  application:
    siteHost: "http://gateway:8000"
    rayHost: "http://kuberay-head-svc:8265"
    auth:
      mechanism: "custom_token"
      token:
        url: "https://auth.quantum-computing.ibm.com/api/users/loginWithToken"
        verificationUrl: "https://auth.quantum-computing.ibm.com/api/users/me"
        verificationField: "ibmQNetwork;urls,services,serverless"
    superuser:
      enable: false
    service:
      type: ClusterIP
      port: 8000
    ray:
      nodeImage: "icr.io/quantum-public/quantum-serverless-ray-node:0.12.0-py310"
      opensslImage: registry.access.redhat.com/ubi8/openssl:8.8-9
      kubectlImage:  alpine/k8s:1.28.9@sha256:4f97e78a640d569731ac71dccc27d7783b03488b383f15ca75ea975d31c3fe57
      cpu: 1
      memory: 1
      replicas: 1
      minReplicas: 1
      maxReplicas: 2
    limits:
      maxJobsPerUser: 2
      maxComputeResources: 5
    proxy:
      enabled: false

  cos:
    claimName: qsafe-program

  secrets:
    secretKey:
      create: false
      name: gateway-secret-key
      key: GATEWAY_SECRET_KEY
    servicePsql:
      create: true
      name: service-psql-binding
      key:
        adminPassword: admin-password
        databaseName: database-name
        databasePassword: database-password
        host: database-host
        port: database-port
        userName: user-name
      value:
        databaseName: serverlessdb
        databasePassword: serverlesspassword
        host: "postgresql"
        port: 5432
        userName: serverlessuser
    superuser:
      create: false

# ===================
# Kuberay Operator
# ===================

kuberayOperatorEnable: true
kuberay-operator:
  image:
    repository: kuberay/operator
    tag: v1.0.0
    pullPolicy: IfNotPresent

# ===================
# PostgreSQL
# ===================

postgresqlEnable: true
postgresql:
  nameOverride: "postgresql"
  fullnameOverride: "postgresql"
  auth:
    enablePostgresUser: false
    database: serverlessdb
    username: serverlessuser
    password: serverlesspassword

# ===================
# COS
# ===================

cosEnable: false
