# Generated by Django 4.2 on 2023-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="arguments",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
