# Generated by Django 4.1 on 2023-03-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.program')),
            ],
        ),
    ]
