# Generated by Django 4.1 on 2023-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='artifact',
            field=models.FileField(default='default', upload_to='artifacts_%Y_%m_%d'),
            preserve_default=False,
        ),
    ]
