# Generated by Django 4.2.1 on 2023-05-23 18:18

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_computeresource_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="artifact",
            field=models.FileField(
                upload_to=core.models.get_upload_path,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["tar"])],
            ),
        ),
    ]
