# Generated by Django 4.1 on 2023-03-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_job_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('ERROR', 'Error'), ('FINISHED', 'Finished')], default='PENDING', max_length=10),
        ),
    ]
