# Generated by Django 4.2.1 on 2023-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_program_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="env_vars",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
