# Generated by Django 4.1 on 2023-03-13 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_computeresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="computeresource",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
