# Generated by Django 4.2.2 on 2023-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_job_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="computeresource",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
