# Generated by Django 4.1 on 2023-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_computeresource_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ray_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
