# Generated by Django 4.2.4 on 2023-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_computeresource_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="logs",
            field=models.TextField(default="No logs yet."),
        ),
    ]
