# Generated by Django 4.2.2 on 2023-09-13 18:11

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_computeresource_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="record revision number"
            ),
        ),
    ]
