# Generated by Django 4.1 on 2023-03-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_job_compute_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("STOPPED", "Stopped"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
