# Generated by Django 4.2.2 on 2023-11-03 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_job_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("auto_scaling", models.BooleanField(default=False, null=True)),
                (
                    "workers",
                    models.IntegerField(
                        null=True,
                    ),
                ),
                (
                    "min_workers",
                    models.IntegerField(
                        null=True,
                    ),
                ),
                (
                    "max_workers",
                    models.IntegerField(
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.jobconfig",
            ),
        ),
    ]
