# Generated by Django 4.2.2 on 2023-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_job_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="primitive_job_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
