# Generated by Django 4.2.2 on 2023-10-19 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_job_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("auto_scaling", models.BooleanField(default=False, null=True)),
                ("workers", models.IntegerField()),
                ("min_workers", models.IntegerField()),
                ("max_workers", models.IntegerField()),
                ("worker_cpu", models.IntegerField()),
                ("worker_mem", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="program",
            name="config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.programconfig",
            ),
        ),
    ]
