# Generated by Django 4.2.2 on 2023-10-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_programconfig_program_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programconfig",
            name="max_workers",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="programconfig",
            name="min_workers",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="programconfig",
            name="worker_cpu",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="programconfig",
            name="worker_mem",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="programconfig",
            name="workers",
            field=models.IntegerField(null=True),
        ),
    ]
