# Generated by Django 4.1 on 2023-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_program_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="arguments",
            field=models.TextField(blank=True, default="{}"),
        ),
        migrations.AddField(
            model_name="program",
            name="dependencies",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
