# Generated by Django 4.2.2 on 2024-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_runtimejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
