# Generated by Django 4.2.2 on 2024-02-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_program_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private"),
                    ("ACTIVE", "Active"),
                    ("PUBLIC", "Public"),
                    ("REVIEWED", "Reviewed"),
                    ("APPROVED", "Approved"),
                ],
                default="PRIVATE",
                max_length=10,
            ),
        ),
    ]
