# Generated by Django 4.2.11 on 2024-03-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_runtimejob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
