# Generated by Django 4.2.11 on 2024-04-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="arguments",
        ),
    ]
