# Generated by Django 4.2.11 on 2024-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="instances",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
