# Generated by Django 4.2.11 on 2024-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0020_remove_program_arguments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={"permissions": (("run_program", "Can run function"),)},
        ),
        migrations.AddField(
            model_name="program",
            name="instances",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
