# Generated by Django 5.0.6 on 2024-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_provider_program_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimejob",
            name="session_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
