# Generated by Django 5.0.6 on 2024-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_provider_program_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
