# Generated by Django 5.0.6 on 2024-06-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_runtimejob_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="runtimejob",
            old_name="session_id",
            new_name="runtime_session",
        ),
    ]
