# Generated by Django 5.0.6 on 2024-06-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_program_description"),
        ("api", "0025_rename_session_id_runtimejob_runtime_session"),
    ]

    operations = []
