# Generated by Django 5.0.7 on 2024-07-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_20240613_1848"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobconfig",
            name="python_version",
        ),
    ]
