# Generated by Django 5.0.7 on 2024-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_20240613_1848"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="admin_group",
        ),
        migrations.AddField(
            model_name="provider",
            name="admin_groups",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
