# Generated by Django 5.0.7 on 2024-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_20240613_1848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobconfig",
            name="python_version",
            field=models.CharField(
                blank=True,
                choices=[
                    ("py38", "Version 3.8"),
                    ("py39", "Version 3.9"),
                    ("py310", "Version 3.10"),
                    ("py311", "Version 3.11"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
