# Generated by Django 5.0.7 on 2024-07-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_jobconfig_python_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobconfig",
            name="python_version",
        ),
    ]
