# Generated by Django 5.1 on 2024-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_provider_admin_group_provider_admin_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="additionalInfo",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("APPLICATION", "Application"),
                    ("CIRCUIT", "Circuit"),
                ],
                default="GENERIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="iconUrl",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
