# Generated by Django 5.1 on 2024-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_program_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="readable_title",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="readable_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
