# Generated by Django 4.2.15 on 2024-10-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_program_readable_title_provider_readable_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="computeresource",
            name="gpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="gpu",
            field=models.BooleanField(default=False),
        ),
    ]
