# Generated by Django 4.2.19 on 2025-03-07 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0033_job_trial_program_trial_instances_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("account", models.TextField(default=None, null=True)),
                (
                    "group",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
