# Generated by Django 4.2.19 on 2025-03-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_serverlessgroup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServerlessGroup",
        ),
    ]
