# Generated by Django 4.2.19 on 2025-03-11 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0035_delete_serverlessgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
