# Generated by Django 4.2.20 on 2025-04-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_groupmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="sub_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAPPING", "Mapping"),
                    ("OPTIMIZING_HARDWARE", "Optimizing for hardware"),
                    ("WAITING_QPU", "Waiting for QPU"),
                    ("EXECUTING_QPU", "Executing in QPU"),
                    ("POST_PROCESSING", "Post-processing"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
