# Generated by Django 4.2.16 on 2025-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_groupmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="public",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
