# Generated by Django 4.2.19 on 2025-04-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_job_sub_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="program",
            name="disabled_message",
            field=models.TextField(
                blank=True,
                default="IBM has temporarily disabled access to this function",
                null=True,
            ),
        ),
    ]
