# Generated by Django 5.2.6 on 2025-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_program_disabled_program_disabled_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="runtime_jobs",
            field=models.JSONField(default=list),
        ),
    ]
