# Generated by Django 5.2.6 on 2025-09-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_program_disabled_program_disabled_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtimejob",
            name="job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runtime_jobs",
                to="api.job",
            ),
        ),
    ]
