# Generated by Django 5.2.8 on 2025-11-14 19:08

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "__first__"),
        ("api", "0039_alter_runtimejob_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ADD", "Add"), ("REMOVE", "Remove")], max_length=255
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("instances", "instances"),
                            ("trial_instances", "trial_instances"),
                        ],
                        max_length=255,
                    ),
                ),
                ("entity", models.CharField(max_length=255)),
                ("entity_id", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255, null=True)),
                ("changed", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.program"
                    ),
                ),
            ],
        ),
    ]
