# Generated by Django 5.2.6 on 2025-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_logconsent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="logconsent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="program",
            name="eula_link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
