# Generated by Django 5.2.11 on 2026-02-12 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_remove_allauth_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("context", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_events",
                        to="api.job",
                    ),
                ),
            ],
        ),
    ]
