# Generated by Django 5.2.11 on 2026-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="version",
            field=models.TextField(null=True, blank=True, default=None),
        ),
    ]
