# Generated by Django 5.2.12 on 2026-03-19 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_program_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeEngineProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "project_id",
                    models.CharField(
                        help_text="IBM Code Engine project UUID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="Code Engine project name in IBM Cloud",
                        max_length=255,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="IBM Cloud region (e.g., us-east, eu-de)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_group_id",
                    models.CharField(help_text="IBM Cloud resource group ID", max_length=255),
                ),
                (
                    "subnet_pool_id",
                    models.CharField(help_text="Subnet pool ID for fleet networking", max_length=255),
                ),
                (
                    "pds_name_state",
                    models.CharField(
                        help_text="Persistent Data Store name for task state",
                        max_length=255,
                    ),
                ),
                (
                    "pds_name_users",
                    models.CharField(help_text="Persistent Data Store name for users", max_length=255),
                ),
                (
                    "pds_name_providers",
                    models.CharField(
                        help_text="Persistent Data Store name for providers",
                        max_length=255,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this project is available for job execution",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="fleet_id",
            field=models.CharField(blank=True, help_text="Code Engine fleet ID", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="compute_resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Ray cluster (for Ray runner)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.computeresource",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="code_engine_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Code Engine project (for Fleets runner)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.codeengineproject",
            ),
        ),
    ]

# Made with Bob
