# Generated by Django 5.2.13 on 2026-04-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_codeengineproject_job_fleet_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="config",
            options={
                "ordering": ["name"],
                "verbose_name": "Configuration",
                "verbose_name_plural": "Config values",
            },
        ),
        migrations.AlterModelOptions(
            name="jobevent",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="codeengineproject",
            name="cos_bucket_name",
            field=models.CharField(
                blank=True,
                help_text="[DEPRECATED] Legacy single bucket field - use cos_bucket_task_store_name instead",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="codeengineproject",
            name="cos_bucket_provider_data_name",
            field=models.CharField(
                blank=True,
                help_text="COS bucket name for provider data (corresponds to pds_name_providers)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="codeengineproject",
            name="cos_bucket_task_store_name",
            field=models.CharField(
                blank=True,
                help_text="COS bucket name for task store (corresponds to pds_name_state)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="codeengineproject",
            name="cos_bucket_user_data_name",
            field=models.CharField(
                blank=True,
                help_text="COS bucket name for user data (corresponds to pds_name_users)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="codeengineproject",
            name="cos_instance_name",
            field=models.CharField(blank=True, help_text="COS instance name", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="codeengineproject",
            name="cos_key_name",
            field=models.CharField(
                blank=True,
                help_text="COS HMAC key name for authentication",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="compute_profile",
            field=models.CharField(
                blank=True,
                help_text="Code Engine compute profile for Fleets runner (e.g., gx3d-24x120x1a100p)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="runner",
            field=models.CharField(
                choices=[("ray", "Ray"), ("fleets", "Fleets")],
                default="ray",
                help_text="Execution backend: ray or fleets",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="default_compute_profile",
            field=models.CharField(
                blank=True,
                help_text="Default Code Engine compute profile for Fleets runner (e.g., gx3d-24x120x1a100p)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="runner",
            field=models.CharField(
                choices=[("ray", "Ray"), ("fleets", "Fleets")],
                default="ray",
                help_text="Execution backend for this program",
                max_length=20,
            ),
        ),
    ]
