# Generated by Django 5.2.13 on 2026-04-23 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_job_business_model_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="business_model",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("SUBSIDIZED", "Subsidized"),
                    ("CONSUMPTION", "Consumption"),
                ],
                default="SUBSIDIZED",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider__isnull", False)),
                fields=("provider", "title"),
                name="unique_provider_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider__isnull", True)),
                fields=("author", "title"),
                name="unique_author_title_no_provider",
            ),
        ),
    ]
