# Generated by Django 5.2.13 on 2026-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_codeengineproject_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="instance_crn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
