# Generated by Django 5.2.15 on 2026-06-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_job_account_id_job_instance_crn"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ce_project_name",
            field=models.CharField(
                blank=True, help_text="CE project name at execution time", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="ce_region",
            field=models.CharField(blank=True, help_text="CE region at execution time", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="code_engine_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Code Engine project for Fleets runner programs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.codeengineproject",
            ),
        ),
        migrations.AlterField(
            model_name="codeengineproject",
            name="zone",
            field=models.CharField(
                blank=True,
                help_text="[DEPRECATED] Kept for rollback compatibility — not used by current code",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="code_engine_project",
            field=models.ForeignKey(
                blank=True,
                help_text="[DEPRECATED] Kept for rollback compatibility — use program.code_engine_project instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.codeengineproject",
            ),
        ),
    ]
