# Generated by Django 5.2.14 on 2026-06-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_job_account_id_job_instance_crn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codeengineproject",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="job",
            name="code_engine_project",
        ),
        migrations.AddField(
            model_name="program",
            name="code_engine_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Code Engine project for Fleets runner programs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.codeengineproject",
            ),
        ),
    ]
