# Generated by Django 5.2.12 on 2026-06-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_add_code_engine_project_to_program_and_job_snapshots"),
        ("api", "0053_program_arguments_schema"),
    ]

    operations = []
