# Generated by Django 5.2.14 on 2026-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_add_code_engine_project_to_program_and_job_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="running_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
