# Generated by Django 5.2.16 on 2026-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_job_running_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="gpu",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether this program should run on GPU nodes. Applies only to the Ray runner; ignored by the Fleets runner.",
            ),
        ),
    ]
