# Generated by Django 5.2.12 on 2026-06-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_job_running_started_at"),
        ("api", "0054_merge_20260616_1707"),
    ]

    operations = []
