# Generated by Django 5.2.16 on 2026-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_job_running_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="gpu",
            field=models.BooleanField(default=False),
        ),
    ]
