# Generated by Django 5.2.12 on 2026-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_job_running_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="arguments_schema",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
    ]
