# Generated by Django 5.2.17 on 2026-08-10 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_program_arguments_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "compute_profile",
                    models.CharField(
                        db_index=True,
                        help_text="Code Engine compute profile identifier (e.g., gx3d-24x120x1a100p)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Human-readable display name / tag for the profile",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("cpu", models.CharField(blank=True, default=None, max_length=64, null=True)),
                ("gpu", models.CharField(blank=True, default=None, max_length=64, null=True)),
                ("memory", models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="flavor",
            field=models.ForeignKey(
                blank=True,
                help_text="Compute profile used by the job, captured at creation time so the historical compute profile is preserved even if the profile changes later.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="api.computeprofile",
            ),
        ),
        migrations.CreateModel(
            name="FunctionSize",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "function_size",
                    models.CharField(choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=1),
                ),
                (
                    "compute_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="function_sizes",
                        to="api.computeprofile",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="function_sizes", to="api.program"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("function", "function_size"), name="unique_function_size")
                ],
            },
        ),
    ]
