# Generated by Django 5.2.17 on 2026-08-17 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_program_arguments_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeProfile",
            fields=[
                (
                    "compute_profile_id",
                    models.CharField(
                        help_text="Code Engine compute profile identifier (e.g., 24x120x1l40)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable display name / tag for the profile (e.g., the size class label)",
                        max_length=255,
                    ),
                ),
                ("cpu", models.CharField(help_text="Number of vCPUs (e.g., 24)", max_length=64)),
                (
                    "gpu",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="GPU allocation as count + model (e.g., 1l40s); null when the profile has no GPUs",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("memory", models.CharField(help_text="Memory in GB (e.g., 120)", max_length=64)),
            ],
        ),
        # The column is dropped from Django's state only, and left in place in the
        # database, so a previous release can still be deployed: its Program model
        # still declares the field, and Django lists every declared column in each
        # SELECT. The real DROP COLUMN happens in a later release.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="program",
                    name="default_compute_profile",
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="job",
            name="compute_profile_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Compute profile used by the job, captured at creation time so the historical compute profile is preserved even if the profile changes later.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="api.computeprofile",
            ),
        ),
        migrations.CreateModel(
            name="FunctionSize",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("function_size", models.CharField(max_length=64)),
                (
                    "compute_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="function_sizes",
                        to="api.computeprofile",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="function_sizes", to="api.program"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="program",
            name="default_size",
            field=models.ForeignKey(
                blank=True,
                help_text="Size used when a run request omits an explicit size. Must belong to this same function.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_functions",
                to="api.functionsize",
            ),
        ),
        migrations.AddConstraint(
            model_name="functionsize",
            constraint=models.UniqueConstraint(fields=("function", "function_size"), name="unique_function_size"),
        ),
    ]
