# Generated by Django 6.0.8 on 2026-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_computeprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeengineproject",
            name="provider_name",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Provider.name this project is dedicated to; empty for the shared default project",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="codeengineproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), models.Q(("provider_name", ""), _negated=True)),
                fields=("provider_name",),
                name="unique_active_ce_project_per_provider",
                violation_error_message="Another active Code Engine project is already dedicated to this provider.",
            ),
        ),
    ]
