# Generated by Django 5.2.17 on 2026-08-25 10:00
#
# This migration produces no SQL: `choices` and `default` are Django-side only, so nothing
# reaches the database. Checked against PostgreSQL 18.4 with `manage.py sqlmigrate api 0058`,
# whose whole output is BEGIN; -- (no-op) COMMIT;, and the api_job.business_model column stays
# a varchar(50) NOT NULL with no database default. Rows keep whatever value they hold, the old
# SUBSIDIZED included.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_computeprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="business_model",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("LICENSED", "Licensed"),
                    ("CONSUMPTION", "Consumption"),
                ],
                default="LICENSED",
                max_length=50,
            ),
        ),
    ]
