# Generated by Django 5.2.17 on 2026-08-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_drop_program_default_compute_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="code_engine_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Code Engine project this provider's Fleets functions run in; empty for the shared default project",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="providers",
                to="api.codeengineproject",
            ),
        ),
    ]
