# Generated by Django 6.0.8 on 2026-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_provider_code_engine_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="filler",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="True when this job was created by the filler-jobs balancer to occupy idle GPU capacity, instead of coming from a real user request.",
            ),
        ),
    ]
