# Generated by Django 6.0.8 on 2026-09-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_provider_code_engine_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="function_size",
            field=models.ForeignKey(
                blank=True,
                help_text="Size row the job resolved to at creation; null when sized by the deployment default profile, the deprecated compute_profile input, or a non-Fleets runner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="api.functionsize",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="size_source",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested by user"),
                    ("DEFAULT_SIZE", "Function default size"),
                    ("SETTINGS_DEFAULT", "Deployment default profile"),
                    ("COMPUTE_PROFILE", "Deprecated compute_profile input"),
                    ("NONE", "Not applicable"),
                ],
                default="NONE",
                help_text="How the job's size/compute profile was determined (requested, defaulted, legacy, or N/A).",
                max_length=32,
            ),
        ),
    ]
