# Generated by Django 6.0.8 on 2026-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_job_filler"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeengineproject",
            name="subnet_pool_name",
            field=models.CharField(
                blank=True,
                help_text="Subnet pool name for fleet networking. When set and subnet_pool_id is empty, the id is resolved from this name on first job submission and cached into subnet_pool_id.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="codeengineproject",
            name="subnet_pool_id",
            field=models.CharField(
                blank=True,
                help_text="Subnet pool ID for fleet networking. May be supplied directly in config, or left empty and resolved from subnet_pool_name (then cached here).",
                max_length=255,
                null=True,
            ),
        ),
    ]
