# Generated by Django 6.0.8 on 2026-09-02 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_job_filler"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(condition=models.Q(("filler", True)), fields=["created"], name="job_filler_true_idx"),
        ),
    ]
