# Generated by Django 5.2.17 on 2026-09-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_job_business_model_licensed"),
        ("api", "0062_job_job_filler_true_idx"),
    ]

    operations = []
