# Generated by Django 5.2.17 on 2026-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_job_fleet_id_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionsize",
            name="function_size",
            field=models.CharField(choices=[("s", "S"), ("m", "M"), ("l", "L"), ("xl", "XL")], max_length=64),
        ),
    ]
