# Generated by Django 6.0.8 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_job_fleet_id_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="plan_id",
            field=models.CharField(
                blank=True,
                help_text="IBM Cloud resource plan ID of the instance, captured at job creation time",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="subscription_id",
            field=models.CharField(
                blank=True,
                help_text="IBM Cloud subscription ID of the instance, captured at job creation time",
                max_length=255,
                null=True,
            ),
        ),
    ]
