# Generated by Django 6.0.8 on 2026-09-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_job_fleet_id_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOutbox",
            fields=[
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="outbox",
                        serialize=False,
                        to="api.job",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                            ("SUCCEEDED", "Succeeded"),
                            ("QUEUED", "Queued"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("status_changed_at", models.DateTimeField()),
                ("has_run", models.BooleanField(default=False)),
                (
                    "workload_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                            ("SUCCEEDED", "Succeeded"),
                            ("QUEUED", "Queued"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("license_fee_required", models.BooleanField()),
                ("license_fee_sent_at", models.DateTimeField(blank=True, null=True)),
                ("billing_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
