# Generated by Django 6.0.8 on 2026-09-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_job_fleet_id_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("STOPPING", "Stopping"),
                    ("STOPPED", "Stopped"),
                    ("SUCCEEDED", "Succeeded"),
                    ("QUEUED", "Queued"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
