# Generated by Django 6.0.8 on 2026-09-25 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_job_fleet_id_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(max_length=20)),
                ("payload", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Not used by delivery: the payload is self-contained. Kept only so a pending row can be found from its job (admin, debugging), without parsing the payload.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.job",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["channel", "created"], name="outbox_channel_created_idx")],
            },
        ),
    ]
