# Generated by Django 6.0.8 on 2026-09-25 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_job_fleet_id_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedCloudResource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("account", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("plan", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("subscription", models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("account", "plan", "subscription"), name="unique_blocked_resource")
                ],
            },
        ),
    ]
