# Generated by Django 6.0.8 on 2026-09-22 17:15

import logging

from django.db import migrations, models
from django.utils import timezone

logger = logging.getLogger("api.migrations.0066_function_size_uppercase_catalog")


def uppercase_existing_function_sizes(apps, schema_editor):
    """Uppercase any function_size row written under the old lowercase convention.

    FunctionSize.save()/from_db() (added alongside this migration) make every row look
    uppercase from here on regardless of what is actually stored, so this is not required
    for correctness going forward. It still runs once so the stored data matches what the
    application believes, avoiding a case where a lowercase row and its uppercased twin
    could otherwise coexist under unique_function_size once both get created for the same
    function. A row is skipped, not overwritten, if its function already has a row at the
    uppercased name (a pre-existing casing collision predating this feature restriction);
    that is a data problem for an operator to resolve by hand, not something a migration
    should silently merge or delete.

    Reads and writes go through .values_list()/.update() rather than model instances on
    purpose: a historical model from apps.get_model() never carries FunctionSize's own
    save()/from_db(), but nothing here should depend on that distinction either way -- a
    plain queryset sees exactly what is in the column, with no normalization in between.
    """
    FunctionSize = apps.get_model("api", "FunctionSize")
    rows = FunctionSize.objects.values_list("pk", "function_id", "function_size")
    for pk, function_id, function_size in rows:
        upper = function_size.upper()
        if upper == function_size:
            continue
        collides = FunctionSize.objects.filter(function_id=function_id, function_size=upper).exclude(pk=pk).exists()
        if collides:
            logger.warning(
                "function_id=%s | function_size %r and %r both exist for this function; leaving %r as is.",
                function_id,
                function_size,
                upper,
                function_size,
            )
            continue
        FunctionSize.objects.filter(pk=pk).update(function_size=upper, updated=timezone.now())


def noop_reverse(apps, schema_editor):
    """Deliberately not reversible: there is no record of which rows were originally lowercase."""


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_function_size_choices"),
    ]

    operations = [
        migrations.RunPython(uppercase_existing_function_sizes, noop_reverse),
        migrations.AlterField(
            model_name="functionsize",
            name="function_size",
            field=models.CharField(choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")], max_length=64),
        ),
    ]
