# Generated by Django 6.0.8 on 2026-09-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_function_size_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionsize",
            name="function_size",
            field=models.CharField(choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")], max_length=64),
        ),
    ]
