# Generated by Django 6.0.8 on 2026-09-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_outbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="size_source",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested by user"),
                    ("DEFAULT_SIZE", "Function default size"),
                    ("SETTINGS_DEFAULT", "Deployment default profile"),
                    ("NONE", "Not applicable"),
                ],
                default="NONE",
                help_text="How the job's size/compute profile was determined (requested, defaulted, legacy, or N/A).",
                max_length=32,
            ),
        ),
    ]
