# Generated by Django 6.0.8 on 2026-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_function_size_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="outbox",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Region of the instance CRN the message belongs to, or null when it has none. Delivery uses it only to pick the circuit breaker: a region that fails does not hold back the others.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="outbox",
            index=models.Index(fields=["channel", "region", "created"], name="outbox_chan_reg_created_idx"),
        ),
    ]
