# Generated by Django 6.0.8 on 2026-10-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_alter_job_size_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="function_size",
            field=models.ForeignKey(
                blank=True,
                help_text="Size row the job resolved to at creation; null when sized by the deployment default profile or a non-Fleets runner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="api.functionsize",
            ),
        ),
    ]
