# Generated by Django 6.0.8 on 2026-10-06 16:17

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_alter_job_function_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="outbox",
            name="attempts",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="How many times sending this row has failed. Delivery uses it to grow the wait between tries.",
            ),
        ),
        migrations.AddField(
            model_name="outbox",
            name="last_error",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Why the last attempt failed, only to find out what is wrong with a row that does not leave.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="outbox",
            name="next_attempt_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
                help_text="The row is not sent before this moment. A new row is due at once, and every failure moves it further away, so a row that always fails cannot keep the rows behind it from being sent.",
            ),
        ),
    ]
