# Generated by Django 6.0.9 on 2026-10-06 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_outbox_retry_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="fleet_deleted_at",
            field=models.DateTimeField(blank=True, help_text="When the fleet delete was accepted", null=True),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(("fleet_deleted_at__isnull", True), ("fleet_id__isnull", False)),
                fields=["updated"],
                name="job_fleet_undeleted_idx",
            ),
        ),
    ]
