# Generated by Django 5.2.17 on 2026-10-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_remove_job_compute_profile_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outbox",
            name="channel",
            field=models.CharField(
                choices=[
                    ("billing_license_fee", "License Fee"),
                    ("billing_job_usage", "Job Usage"),
                    ("workload", "Workload"),
                ],
                max_length=20,
            ),
        ),
    ]
