{{- if .Values.useCertManager }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-cluster-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ray-cluster-role
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ray-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ray-cluster-role
subjects:
- kind: ServiceAccount
  name: ray-cluster-sa
{{- end }}