{{- if .Values.prometheusEnable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-head-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  jobLabel: ray-head
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
    - port: metrics
  targetLabels:
  - ray.io/cluster
{{- end }}
