name: 'Build and push images'
description: 'Builds and pushes images to remote repository'
inputs:
  name:
    description: 'Image name'
    required: true
  tag:
    description: 'Release version'
    required: true
  dockerfile:
    description: 'Location of dockerfile'
    required: true
  platforms:
    description: '(optional) platform to build image for'
    required: false
    default: "linux/amd64"
  repository:
    description: '(optional) repository'
    required: false
    default: 'icr.io/quantum-public'
  pythonversion:
    description: '(optional) python version'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        platforms: ${{inputs.platforms}}
        context: .
        file: ${{inputs.dockerfile}}
        push: true
        tags: ${{inputs.repository}}/${{inputs.name}}:${{inputs.tag}},${{inputs.repository}}/${{inputs.name}}:latest
