apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-istio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: gateway-https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: qc-ibm-com
    hosts:
    - middleware-dev.quantum-computing.ibm.com

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway-virtual-service
spec:
  hosts:
  - middleware-dev.quantum-computing.ibm.com
  gateways:
  - gateway-istio
  http:
  - route:
    - destination:
        host: gateway
        port:
          number: 8000
