apiVersion: v1
kind: Secret
metadata:
  name: ca-tls
data:
  # cat ca.crt | base64
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVVzQyUDZxZVEr
    MU54M2xzazFaY2hCTjhSUmhnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURVdNQlFHQTFVRUF3d05L
    aTVyZFdKbGNtRjVMbU52YlRFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQmdOVgpCQWNNRFZOaGJpQkdj
    bUZ1WTJselkyOHdIaGNOTWpNd016STJNREUxT1RNeVdoY05Nek13TXpJek1ERTFPVE15CldqQTlN
    Ull3RkFZRFZRUUREQTBxTG10MVltVnlZWGt1WTI5dE1Rc3dDUVlEVlFRR0V3SlZVekVXTUJRR0Ex
    VUUKQnd3TlUyRnVJRVp5WVc1amFYTmpiekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFE
    Q0NBUW9DZ2dFQgpBTkh5Yk1PWjNlZ2hZS0gzTVJlcVhqSU83QlRHUGk3NXJ0ekpsMjN5WVhRdEFP
    Y050eVNxZUllVk43YnJIYzAyCkN1RXNocUNpSHBDeVdYcDlVMWRCYlZwYWU3OXc3R1AySHBJclBr
    WXZITm5ZZEF3a0dnYkpTeTNPSkJOb2N0MUEKbVdwYWI5N243dGlFbkw1bFFsR01vejBwR0FYQ1BK
    Q3lVTWtsbDE2eUlSVUtjdjZkZThBcWZMU0FPRmxIY1BHRQo1SnhpRlhJcWtzbStqN0txZDVqQk14
    b1RCV0puVmk4MTRVZ3U4eEMxZkV2ZlRKM1hMeWZ6cmtIbkJHZGYyUG4wCkJHVWtobzB3dDNoSGVt
    QUs4NXV2OWZIUUdNMlpZOTYxVzhFT2ZQL3pCT3FIODZZMG9hU0VUQlpiSm45WEg2Y2UKdnIvWW9z
    OU1wQU52K3dpemhqZFVPUWNDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkh2bk81LzdjakVMVXpt
    NwpiaUJSay9Qc2N5dDdNQjhHQTFVZEl3UVlNQmFBRkh2bk81LzdjakVMVXptN2JpQlJrL1BzY3l0
    N01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTHg1cXZW
    VUQvNVMwUjE2UUpFTWRlS3IKQzhaazhPL2dMa3ZkTlNEeUVzam5zU1JKWFF5aW4zdEJXQjhLaSs3
    VXBlQ3Y4TCtjOUdHM05oNzBUdGhxTmNrOApHT0ZHVHdYTi9XLy9MbTNIZEJVK2UzSkJkbElOTEo4
    alRuRjFQUXJvS2ZacURCZnVlR0FwSDdPT0JKYWl2KzFtCjdxalNsbkovYS9rRlRaWXNsNVpZU204
    dWI4Q3RGQnFwOFliM0xBcU5YUG9zL3QzVFBVbG1wRHpOK0lPTTBSb1IKKy9vS3A3TUpCNFFoeFQ2
    T2RYVy9Iekw3bndmbnZ6QU12NXREKzdUamJuaDFrS0d2b0ZBUW5neXRMQnAzcllxcQpBRWFYck8x
    OUFNKzdCMmpQcHB4RVM1Rm01K3FPdS9BUnBzVDdzbUJ0eitudnlwdEM3Y2J2QUZzZFAwRnhHWjA9
    Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  # cat ca.key | base64
  ca.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV1d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktVd2dnU2hBZ0VBQW9JQkFRRFI4bXpEbWQzb0lXQ2gKOXpFWHFsNHlEdXdVeGo0dSthN2N5
    WmR0OG1GMExRRG5EYmNrcW5pSGxUZTI2eDNOTmdyaExJYWdvaDZRc2xsNgpmVk5YUVcxYVdudS9j
    T3hqOWg2U0t6NUdMeHpaMkhRTUpCb0d5VXN0emlRVGFITGRRSmxxV20vZTUrN1loSnkrClpVSlJq
    S005S1JnRndqeVFzbERKSlpkZXNpRVZDbkwrblh2QUtueTBnRGhaUjNEeGhPU2NZaFZ5S3BMSnZv
    K3kKcW5lWXdUTWFFd1ZpWjFZdk5lRklMdk1RdFh4TDMweWQxeThuODY1QjV3Um5YOWo1OUFSbEpJ
    YU5NTGQ0UjNwZwpDdk9ici9YeDBCak5tV1BldFZ2QkRuei84d1RxaC9PbU5LR2toRXdXV3laL1Z4
    K25IcjYvMktMUFRLUURiL3NJCnM0WTNWRGtIQWdNQkFBRUNnZ0VBQkx0RzhqMlVmN2ZJMnIyY2NL
    RVpVRjEvdXBRaE1LUFY2Z250RE1CS3EvaWIKclpsa2lFSURSMkw0aDNuVENSM3ZydFYzRDBXNEZL
    REFYWDlYa243Wi9SQk8rNmlLMjFIZnJJR20vS1B4TFlPdwpVZG02Y0c2MjhBaFdUYzJyMFFxMHFt
    M3hXWCsycFZDUHk4YXljTzRQZThCaVZ6YmljSXhrUDdSR0xnOHJxYkt4CkhYM1pOUnhIUy9NOW9X
    YzYyM2RTZEJwZGdxUitLYlVVM21aWjJXc3ZBSjZiME5sZ0U0Vkc4aTFqUFBLbDVFV2kKRmtnTkVG
    N0pNZ0RHRDQvODEvMlErUnRCdmtpQTlmZkk0NER4Z04rbVJBZmVaRFQvZWtOTDROVlRUWm9SZkpk
    YwpKcGtqMmppNE5NUENJTGNnazN5QVBuSXRTamlsWGkrMXFiTjNmZXQwV1FLQmdRRDRGOTBreWhy
    K0p1cWRrMnIwCjZPTXVVSk9GM3k0UDA2OFFOTHF4blNPOERaMndKL2cwdGJhWk5Senp4anZwWHFZ
    VVpIWGVhVHdNYkNreE55TnEKb0kvQmYwYTJoUGcyeE9iTm5HVUF6MEgzVGZ2Y0JvcVIvVXlOTFZr
    d0dtUUx5WVZuNWdmSXdnN1lsS2x2emtsegp3aHUxNnNSVGNPNXpBUkpaTHV3dy9MSWFjd0tCZ1FE
    WW8xV2Z3N1pWeUQrSSszRlRMbzhCeXJZd2F2S3FjY1dQCjM5T20wdzB2ckZTc0tHQVFnY0ZwR2NX
    cG5FM0FMWnZ6eHAyU2lRTkc0RkhWTmNZblNqM0tKY2lGRC9vOHJRSTgKNjRxOE82MW9QL2lQOWNt
    MzFpNjRCYmhsaFhqeUZPZGc4bU9LSWZnOHB2Y1AzeDBMKzdRMy9GbmIzWmxkd1lkdAo5SjhXbDR0
    ZUhRS0JnUUN4czNZbENkWjN3S3hBSGYxNFd1K09sd3h6MFQ0Ty9CTGl5c0lHd29WOEIweXhobytV
    ClFhdis1VHBOcWVuejZHV1JLYnY3aU9rSUJOa2tkVmdhNGRMV1NESUFQaElFT05rUTRUcS9iN1RT
    VEx0Z0NCZHQKSmorVXg2eWdkZWEvUXFNWm5ueG80Z2I4UHM5MlZBM3NxbFpxNFRPcWlMTmpFSnR4
    NGRndjVuQXozUUtCZ0dtSwphVlNFVEhoT0xtWFYyY2ZranRjWW90bkR3S1U0K0Q2M2xLMVpkTHNk
    QWNNOWlFK0NaMitFbHIraTNsNFoyamhSCk1zTUk3UWZDa1J1R0x4dEZHQVU3a3cwQVU3RHJ1SU5s
    WFJtSEdWd0lqbGZVTG9uWlZybGdVQTFsa1I2ZkFIcEMKbkN2WGtOQTdwM0djQ05LbHRZN3c2Zlly
    WjJROXZIVGRFQVE1b0RRaEFuOCtwUFFySEZ1aHhWMnBGb0RjcFFCSApPR0NjbHZJUGxOZTZzWmFO
    YXQwb0pjUDkxbkI3TFoxMnVhUG9wa3dZckxGZXBtQVRiOElDbU9LMGNCUWNIenljCm5tM3lWVEt1
    LzA1NnMvdVQwSnY3dFA0clluR3c3WG5acWV1bVNzd2pqbTZIRHBRNG5Ia1JmWFZ5VkVBZFVONUsK
    VVc3Q01ubkQ2OGsranZLc2lXbmYKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tls
data:
  gencert_head.sh: |
    #!/bin/sh
    ## Create tls.key
    openssl genrsa -out /etc/ray/tls/tls.key 2048

    ## Write CSR Config
    cat > /etc/ray/tls/csr.conf <<EOF
    [ req ]
    default_bits = 2048
    prompt = no
    default_md = sha256
    req_extensions = req_ext
    distinguished_name = dn

    [ dn ]
    C = US
    ST = California
    L = San Fransisco
    O = test
    OU = test
    CN = *.kuberay.com

    [ req_ext ]
    subjectAltName = @alt_names

    [ alt_names ]
    DNS.1 = localhost
    DNS.2 = $FQ_RAY_IP
    IP.1 = 127.0.0.1
    IP.2 = $POD_IP

    EOF

    ## Create CSR using tls.key
    openssl req -new -key /etc/ray/tls/tls.key -out /etc/ray/tls/ca.csr -config /etc/ray/tls/csr.conf

    ## Write cert config
    cat > /etc/ray/tls/cert.conf <<EOF

    authorityKeyIdentifier=keyid,issuer
    basicConstraints=CA:FALSE
    keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
    subjectAltName = @alt_names

    [alt_names]
    DNS.1 = localhost
    DNS.2 = $FQ_RAY_IP
    IP.1 = 127.0.0.1
    IP.2 = $POD_IP

    EOF

    ## Generate tls.cert
    openssl x509 -req \
        -in /etc/ray/tls/ca.csr \
        -CA /etc/ray/tls/ca.crt -CAkey /etc/ray/tls/ca.key \
        -CAcreateserial -out /etc/ray/tls/tls.crt \
        -days 365 \
        -sha256 -extfile /etc/ray/tls/cert.conf

  gencert_worker.sh: |
    #!/bin/sh
    ## Create tls.key
    openssl genrsa -out /etc/ray/tls/tls.key 2048

    ## Write CSR Config
    cat > /etc/ray/tls/csr.conf <<EOF
    [ req ]
    default_bits = 2048
    prompt = no
    default_md = sha256
    req_extensions = req_ext
    distinguished_name = dn

    [ dn ]
    C = US
    ST = California
    L = San Fransisco
    O = test
    OU = test
    CN = *.kuberay.com

    [ req_ext ]
    subjectAltName = @alt_names

    [ alt_names ]
    DNS.1 = localhost
    IP.1 = 127.0.0.1
    IP.2 = $POD_IP

    EOF

    ## Create CSR using tls.key
    openssl req -new -key /etc/ray/tls/tls.key -out /etc/ray/tls/ca.csr -config /etc/ray/tls/csr.conf

    ## Write cert config
    cat > /etc/ray/tls/cert.conf <<EOF

    authorityKeyIdentifier=keyid,issuer
    basicConstraints=CA:FALSE
    keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
    subjectAltName = @alt_names

    [alt_names]
    DNS.1 = localhost
    IP.1 = 127.0.0.1
    IP.2 = $POD_IP

    EOF

    ## Generate tls.cert
    openssl x509 -req \
        -in /etc/ray/tls/ca.csr \
        -CA /etc/ray/tls/ca.crt -CAkey /etc/ray/tls/ca.key \
        -CAcreateserial -out /etc/ray/tls/tls.crt \
        -days 365 \
        -sha256 -extfile /etc/ray/tls/cert.conf
{{- if .Values.useCertManager }}
  gencert_cert_head.sh: |
    #!/bin/sh
    BASE_DIR=$1
    CLUSTER_NAME=$2
    IP_ADDRESS=$3
    NAMESPACE=$4

    kubectl apply -f - <<EOF
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: $CLUSTER_NAME
    spec:
      commonName: quantummiddleware.com
      dnsNames:
      - localhost
      - $CLUSTER_NAME-head-svc.$NAMESPACE.svc.cluster.local
      duration: 2160h0m0s
      ipAddresses:
      - 127.0.0.1
      - $IP_ADDRESS
      issuerRef:
        group: cert-manager.io
        kind: Issuer
        name: ray-ca-issuer
      privateKey:
        algorithm: RSA
        encoding: PKCS1
        size: 2048
      renewBefore: 360h0m0s
      secretName: $CLUSTER_NAME
      subject:
        organizations:
        - quantummiddleware
      usages:
      - server auth
      - client auth
    EOF

    status="False"
    while [ $status = "False" ]
    do
        status=$(kubectl get cert $CLUSTER_NAME -o=jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
    done

    echo "Certificate for $CLUSTER_NAME is ready"
    kubectl get cert $CLUSTER_NAME -o json

    kubectl get secret $CLUSTER_NAME -o=jsonpath='{.data.ca\.crt}' | base64 -d > $BASE_DIR/ca.crt
    kubectl get secret $CLUSTER_NAME -o=jsonpath='{.data.tls\.crt}' | base64 -d > $BASE_DIR/tls.crt
    kubectl get secret $CLUSTER_NAME -o=jsonpath='{.data.tls\.key}' | base64 -d > $BASE_DIR/tls.key
  gencert_cert_worker.sh: |
    #!/bin/sh
    BASE_DIR=$1
    CLUSTER_NAME=$2
    IP_ADDRESS=$3

    kubectl apply -f - <<EOF
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: $CLUSTER_NAME-worker
    spec:
      commonName: quantummiddleware.com
      dnsNames:
      - localhost
      duration: 2160h0m0s
      ipAddresses:
      - 127.0.0.1
      - $IP_ADDRESS
      issuerRef:
        group: cert-manager.io
        kind: Issuer
        name: ray-ca-issuer
      privateKey:
        algorithm: RSA
        encoding: PKCS1
        size: 2048
      renewBefore: 360h0m0s
      secretName: $CLUSTER_NAME-worker
      subject:
        organizations:
        - quantummiddleware
      usages:
      - server auth
      - client auth
    EOF

    status="False"
    while [ $status = "False" ]
    do
        status=$(kubectl get cert $CLUSTER_NAME-worker -o=jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
    done

    echo "Certificate for $CLUSTER_NAME-worker is ready"
    kubectl get cert $CLUSTER_NAME-worker -o json

    kubectl get secret $CLUSTER_NAME-worker -o=jsonpath='{.data.ca\.crt}' | base64 -d > $BASE_DIR/ca.crt
    kubectl get secret $CLUSTER_NAME-worker -o=jsonpath='{.data.tls\.crt}' | base64 -d > $BASE_DIR/tls.crt
    kubectl get secret $CLUSTER_NAME-worker -o=jsonpath='{.data.tls\.key}' | base64 -d > $BASE_DIR/tls.key
{{- end }}