{{- if .Values.secrets.servicePsql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.servicePsql.name  }}
stringData:
  {{ .Values.secrets.servicePsql.key.databaseName }}: {{ .Values.secrets.servicePsql.value.databaseName }}
  {{ .Values.secrets.servicePsql.key.databasePassword }}: {{ .Values.secrets.servicePsql.value.databasePassword }}
  {{ .Values.secrets.servicePsql.key.host }}: {{ .Values.secrets.servicePsql.value.host }}
  {{ .Values.secrets.servicePsql.key.port }}: {{ .Values.secrets.servicePsql.value.port | quote }}
  {{ .Values.secrets.servicePsql.key.userName }}: {{ .Values.secrets.servicePsql.value.userName }}
{{ end }}
