{{- if .Values.secrets.superuser.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.superuser.name  }}
stringData:
  {{ .Values.secrets.superuser.key.name }}: {{ .Values.secrets.superuser.value.name }}
  {{ .Values.secrets.superuser.key.password }}: {{ .Values.secrets.superuser.value.password }}
  {{ .Values.secrets.superuser.key.email }}: {{ .Values.secrets.superuser.value.email }}
{{ end }}
