FROM icr.io/quantum-public/quantum-serverless-ray-node:0.9.0-py39

# install all necessary dependencies for your custom image

# copy our function implementation in `/runner.py` of the docker image
COPY ./runner.py ./runner.py
