"""Constants."""

import os

META_TOPIC: str = "execution-meta"

QS_EXECUTION_WORKLOAD_ID: str = "QS_EXECUTION_WORKLOAD_ID"
QS_EXECUTION_UID: str = "QS_EXECUTION_UID"

# telemetry
QS_OT_PROGRAM_NAME = "QS_OT_PROGRAM_NAME"
OT_PROGRAM_NAME_DEFAULT = "unnamed_execution"
OTEL_EXPORTER_OTLP_HOST = "OTEL_EXPORTER_OTLP_HOST"
OTEL_EXPORTER_OTLP_PORT = "OTEL_EXPORTER_OTLP_PORT"
QS_OT_TRACEPARENT_ID_KEY = "QS_OT_TRACEPARENT_ID_KEY"
OTEL_EXPORTER_OTLP_INSECURE = "OTEL_EXPORTER_OTLP_INSECURE"
OTEL_ENABLED = "OTEL_ENABLED"
QS_OT_RAY_TRACER = "QS_OT_RAY_TRACER"
OT_SPAN_DEFAULT_NAME = "entrypoint"
OT_ATTRIBUTE_PREFIX = "qs"
OT_LABEL_CALL_LOCATION = "qs.location"

# request timeout
REQUESTS_TIMEOUT_DEFAULT: int = 30
REQUESTS_TIMEOUT_OVERRIDE = "REQUESTS_TIMEOUT_OVERRIDE"
REQUESTS_STREAMING_TIMEOUT_DEFAULT: int = 60
REQUESTS_STREAMING_TIMEOUT_OVERRIDE = "REQUESTS_TIMEOUT_OVERRIDE"

# gateway
ENV_GATEWAY_PROVIDER_HOST = "ENV_GATEWAY_PROVIDER_HOST"
ENV_GATEWAY_PROVIDER_VERSION = "ENV_GATEWAY_PROVIDER_VERSION"
ENV_GATEWAY_PROVIDER_TOKEN = "ENV_GATEWAY_PROVIDER_TOKEN"
GATEWAY_PROVIDER_VERSION_DEFAULT = "v1"

# auth
ENV_JOB_GATEWAY_TOKEN = "ENV_JOB_GATEWAY_TOKEN"
ENV_JOB_GATEWAY_INSTANCE = "ENV_JOB_GATEWAY_INSTANCE"
ENV_JOB_GATEWAY_HOST = "ENV_JOB_GATEWAY_HOST"
ENV_JOB_ID_GATEWAY = "ENV_JOB_ID_GATEWAY"
ENV_JOB_ARGUMENTS = "ENV_JOB_ARGUMENTS"
QISKIT_IBM_CHANNEL = "QISKIT_IBM_CHANNEL"

DATA_PATH = "DATA_PATH"

# job
ENV_ACCESS_TRIAL = "ENV_ACCESS_TRIAL"

# artifact
MAX_ARTIFACT_FILE_SIZE_MB_DEFAULT = 50
MAX_ARTIFACT_FILE_SIZE_MB_OVERRIDE = "MAX_ARTIFACT_FILE_SIZE_MB_OVERRIDE"

# IBM urls
IBM_SERVERLESS_HOST_URL_DEFAULT = "https://qiskit-serverless.quantum.ibm.com"
IBM_SERVERLESS_HOST_URL_OVERRIDE = "IBM_SERVERLESS_HOST_URL_OVERRIDE"

REQUESTS_TIMEOUT = int(os.getenv(REQUESTS_TIMEOUT_OVERRIDE, default=str(REQUESTS_TIMEOUT_DEFAULT)))

REQUESTS_STREAMING_TIMEOUT = int(
    os.getenv(
        REQUESTS_STREAMING_TIMEOUT_OVERRIDE,
        default=str(REQUESTS_STREAMING_TIMEOUT_DEFAULT),
    )
)

MAX_ARTIFACT_FILE_SIZE_MB = int(
    os.getenv(
        MAX_ARTIFACT_FILE_SIZE_MB_OVERRIDE,
        default=str(MAX_ARTIFACT_FILE_SIZE_MB_DEFAULT),
    )
)
IBM_SERVERLESS_HOST_URL = os.getenv(IBM_SERVERLESS_HOST_URL_OVERRIDE, default=IBM_SERVERLESS_HOST_URL_DEFAULT)
