{{- if .Values.prometheusEnable }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
    release: {{ .Release.Name }}
  name: ray-joblogs-dashboard
  namespace: {{ .Release.Namespace }}
data:
  ray-joblogs.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "description": "Job logs",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 36,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": "P982945308D3682D1"
          },
          "gridPos": {
            "h": 22,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Ascending",
            "wrapLogMessage": false
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P982945308D3682D1"
              },
              "editorMode": "code",
              "expr": "{container=\"ray-head-logs\"}",
              "key": "Q-afd4b3ce-5d5b-4063-98eb-6ebf00d7c7db-0",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Job Execution Logs",
          "type": "logs"
        }
      ],
      "refresh": "",
      "revision": 1,
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Job Logs",
      "uid": "87ZLGa84z",
      "version": 1,
      "weekStart": ""
    }
{{- end }}
