"""
Django settings for gateway project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import os.path
import sys
from datetime import timedelta
from pathlib import Path
from utils import sanitize_file_path

from config import Config

RELEASE_VERSION = Config.version()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Config.secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Config.debug()

# SECURITY WARNING: don't run with debug turned on in production!
LOG_LEVEL = Config.log_level()

# It must be a full url without protocol: mydomain.com
ALLOWED_HOSTS = Config.allowed_hosts()

# It must be a full url: https://mydomain.com
CSRF_TRUSTED_ORIGINS = Config.csrf_trusted_origins()

# It must be a regex compatible: ^https://\w+\.example\.com$
CORS_ALLOWED_ORIGIN_REGEXES = Config.cors_allowed_origin_regexes()

# allow connections from any kubernetes pod within the cluster
# k8s pods are given an IP on the private 10. network, and 10.0.0.0/8
# includes all 10. IPs.
ALLOWED_CIDR_NETS = ["10.0.0.0/8"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_prometheus",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "allauth",
    "allauth.socialaccount",
    "api",
    "psycopg2",
    "drf_yasg",
    "corsheaders",
    "csp",
]

MIDDLEWARE = [
    "main.middleware.add_slash",
    "corsheaders.middleware.CorsMiddleware",
    "csp.middleware.CSPMiddleware",
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "main.middleware.current_user_context",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", "/tmp/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(levelname)s %(asctime)s %(filename)s:%(lineno)s : %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "commands": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gateway": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gateway.serializers": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gateway.authentication": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": Config.database_name(),
        "USER": Config.database_user(),
        "PASSWORD": Config.database_password(),
        "HOST": Config.database_host(),
        "PORT": Config.database_port(),
    },
    "test": {
        "ENGINE": "django_prometheus.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

if "test" in sys.argv:
    DATABASES["default"] = DATABASES["test"]

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(sanitize_file_path(str(BASE_DIR)), "static")

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(sanitize_file_path(str(BASE_DIR)), "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============
# AUTH SETTINGS
# =============
SETTINGS_AUTH_MECHANISM = Config.auth_mechanism()
SETTINGS_DEFAULT_AUTH_CLASSES = [
    "rest_framework_simplejwt.authentication.JWTAuthentication",
    "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
]
ALL_AUTH_CLASSES_CONFIGURATION = {
    "default": SETTINGS_DEFAULT_AUTH_CLASSES,
    "custom_token": [
        "api.authentication.CustomTokenBackend",
    ],
    "mock_token": [
        "api.authentication.MockTokenBackend",
    ],
}
DJR_DEFAULT_AUTHENTICATION_CLASSES = ALL_AUTH_CLASSES_CONFIGURATION.get(
    SETTINGS_AUTH_MECHANISM, SETTINGS_DEFAULT_AUTH_CLASSES
)
# mock token value
SETTINGS_AUTH_MOCK_TOKEN = Config.auth_mock_token()
SETTINGS_AUTH_MOCKPROVIDER_REGISTRY = Config.auth_mockprovider_registry()
# =============

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": DJR_DEFAULT_AUTHENTICATION_CLASSES,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
}

REST_AUTH = {
    "USE_JWT": True,
    # 'JWT_AUTH_COOKIE': 'gateway-app-auth',
    # 'JWT_AUTH_REFRESH_COOKIE': 'gateway-refresh-token',
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer Token": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        },
    },
    "USE_SESSION_AUTH": False,
}

SITE_ID = 1
SITE_HOST = Config.site_host()

# Provider specific settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=20),
}

# custom token auth
QUANTUM_PLATFORM_API_BASE_URL = Config.quantum_platform_api_base_url()
# verification fields to check when returned from auth api
# Example of checking multiple fields:
#    For following verification data
#    {
#       "is_valid": true,
#       "some": {
#         "nested": {
#           "field": true
#         },
#         "other": "bla"
#       }
#    }
#   setting string will be:
#    "SETTINGS_TOKEN_AUTH_VERIFICATION_FIELD", "is_valid;some,nested,field"
SETTINGS_TOKEN_AUTH_VERIFICATION_FIELD = Config.token_auth_verification_field()

# resources limitations
LIMITS_JOBS_PER_USER = Config.limits_jobs_per_user()
LIMITS_MAX_CLUSTERS = Config.limits_max_clusters()
LIMITS_GPU_CLUSTERS = Config.limits_gpu_clusters()
LIMITS_CPU_PER_TASK = Config.limits_cpu_per_task()
LIMITS_GPU_PER_TASK = Config.limits_gpu_per_task()
LIMITS_MEMORY_PER_TASK = Config.limits_memory_per_task()
MAINTENANCE = Config.maintenance()

# ray cluster management
RAY_KUBERAY_NAMESPACE = Config.ray_kuberay_namespace()
RAY_CLUSTER_MODE = {
    "local": Config.ray_cluster_mode_local(),
    "ray_local_host": Config.ray_cluster_mode_local_host(),
}
RAY_NODE_IMAGE = Config.ray_node_image()
RAY_CLUSTER_WORKER_REPLICAS = Config.ray_cluster_worker_replicas()
RAY_CLUSTER_WORKER_REPLICAS_MAX = Config.ray_cluster_worker_replicas_max()
RAY_CLUSTER_WORKER_MIN_REPLICAS = Config.ray_cluster_worker_min_replicas()
RAY_CLUSTER_WORKER_MIN_REPLICAS_MAX = Config.ray_cluster_worker_min_replicas_max()
RAY_CLUSTER_WORKER_MAX_REPLICAS = Config.ray_cluster_worker_max_replicas()
RAY_CLUSTER_WORKER_MAX_REPLICAS_MAX = Config.ray_cluster_worker_max_replicas_max()
RAY_CLUSTER_WORKER_AUTO_SCALING = Config.ray_cluster_worker_auto_scaling()
RAY_CLUSTER_MAX_READINESS_TIME = Config.ray_cluster_max_readiness_time()
RAY_SETUP_MAX_RETRIES = Config.ray_setup_max_retries()
RAY_CLUSTER_NO_DELETE_ON_COMPLETE = Config.ray_cluster_no_delete_on_complete()
RAY_CLUSTER_CPU_NODE_SELECTOR_LABEL = Config.ray_cluster_cpu_node_selector_label()
RAY_CLUSTER_GPU_NODE_SELECTOR_LABEL = Config.ray_cluster_gpu_node_selector_label()
PROGRAM_TIMEOUT = Config.program_timeout()
GATEWAY_ALLOWLIST_CONFIG = Config.gateway_allowlist_config()
GATEWAY_GPU_JOBS_CONFIG = Config.gateway_gpu_jobs_config()
GATEWAY_DYNAMIC_DEPENDENCIES = Config.gateway_dynamic_dependencies()

# authentication base url for qiskit runtime
QISKIT_IBM_URL = Config.qiskit_ibm_url()

# quantum api
IQP_QCON_API_BASE_URL = Config.iqp_qcon_api_base_url()

# IBM Cloud
IAM_IBM_CLOUD_BASE_URL = Config.iam_ibm_cloud_base_url()
RESOURCE_CONTROLLER_IBM_CLOUD_BASE_URL = Config.resource_controller_ibm_cloud_base_url()
RESOURCE_PLANS_ID_ALLOWED = Config.resource_plans_id_allowed()

# Content Security Policy
CSP_DEFAULT_SRC = "'none'"
CSP_SCRIPT_SRC = "'none'"
CSP_FRAME_ANCESTORS = "'self'"
CSP_OBJECT_SRC = "'self'"
CSP_IMG_SRC = ("'self'", "data:")
CSP_STYLE_SRC_ELEM = "'self'"
CSP_SCRIPT_SRC_ELEM = "'self'"
CSP_CONNECT_SRC = "'self'"
CSP_WORKER_SRC = ("'self'", "blob:")

# Custom image for programs settings
CUSTOM_IMAGE_PACKAGE_NAME = Config.custom_image_package_name()
CUSTOM_IMAGE_PACKAGE_PATH = Config.custom_image_package_path()
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_AGE = 3600

# Functions logs size limite in MB
FUNCTIONS_LOGS_SIZE_LIMIT = Config.functions_logs_size_limit()
