FROM registry.access.redhat.com/ubi9/python-39@sha256:89463fe3e086620617a4f6281640469ba7a7abd2f1b5be13e6cf0f46a6565516

WORKDIR /app

USER 0
COPY repository .
RUN chown -R 1001:0 /app
USER 1001

RUN pip3 install -r requirements.txt
RUN pip3 install -r requirements-dev.txt

RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

EXPOSE 8060
# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

