FROM python:3.9.16-slim-buster

WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apt-get -y update && apt-get -y upgrade &&  apt-get -y install gcc python3-dev

USER 0
COPY gateway .
RUN chown -R 1001:0 /usr/src/app

RUN pip install -r requirements.txt

USER 1001

RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

EXPOSE 8000
# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
