FROM jupyter/base-notebook:python-3.7

USER $NB_UID

COPY --chown=$NB_UID:$NB_UID ./client ./qs
RUN cd ./qs && pip install .
RUN cd ../
RUN rm -r ./qs

COPY --chown=$NB_UID:$NB_UID ./docs/tutorials/ ./serverless/tutorials/
COPY --chown=$NB_UID:$NB_UID ./docs/guides/ ./serverless/guides/

ENV JUPYTER_ENABLE_LAB=no
