ARG IMAGE_PY_VERSION=3.9
FROM jupyter/base-notebook:python-$IMAGE_PY_VERSION

USER 0
RUN apt-get -y update && apt-get -y install gcc build-essential libopenblas-dev

USER $NB_UID

COPY --chown=$NB_UID:$NB_UID ./client ./qs
RUN cd ./qs && pip install .
RUN pip install ipywidgets
RUN cd ../
RUN rm -r ./qs

RUN git clone https://github.com/Qiskit-Extensions/circuit-knitting-toolbox.git ckt && cd ckt && pip install . && cd ../ && rm -r ./ckt

COPY --chown=$NB_UID:$NB_UID ./docs/tutorials/ ./serverless/tutorials/
COPY --chown=$NB_UID:$NB_UID ./docs/guides/ ./serverless/guides/
COPY --chown=$NB_UID:$NB_UID ./docs/getting_started/ ./serverless/getting_started/

ENV JUPYTER_ENABLE_LAB=no
