FROM python:3.11.4-slim-buster

WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

USER 0
COPY repository .
RUN chown -R 1001:0 /usr/src/app

RUN pip install -r requirements.txt

USER 1001

RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

EXPOSE 8060
# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

