FROM python:3.9.16-slim-buster

WORKDIR /app

USER 0
COPY repository .
RUN chown -R 1001:0 /app

RUN pip3 install -r requirements.txt
RUN pip3 install -r requirements-dev.txt
RUN python manage.py migrate
USER 1001

EXPOSE 8060
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8060"]

