ARG IMAGE_PY_VERSION=py39
ARG TARGETPLATFORM

FROM rayproject/ray:2.4.0-$IMAGE_PY_VERSION AS ray-node-linux/amd64

USER $RAY_UID
COPY --chown=$RAY_UID:$RAY_UID ./client ./qs
RUN cd ./qs && pip install .
RUN cd ../ 
RUN rm -r ./qs

FROM rayproject/ray:2.4.0-$IMAGE_PY_VERSION-aarch64 AS ray-node-linux/arm64

USER $RAY_UID
RUN apt-get -y update && apt-get -y install gcc build-essential libopenblas-dev cmake
COPY --chown=$RAY_UID:$RAY_UID ./client ./qs
RUN cd ./qs && pip install .
RUN if [ $TARGETPLATFORM == linux/arm64 ] ; then pip install git+https://github.com/pyscf/pyscf@v2.2.1; fi
RUN cd ../
RUN rm -r ./qs

FROM ray-node-${TARGETPLATFOEM} AS final
