ARG IMAGE_PY_VERSION=py39
FROM rayproject/ray:2.4.0-$IMAGE_PY_VERSION-aarch64
USER $RAY_UID

RUN apt-get -y update && apt-get -y install gcc build-essential libopenblas-dev cmake
COPY --chown=$RAY_UID:$RAY_UID ./client ./qs
RUN cd ./qs && pip install .
RUN pip install git+https://github.com/pyscf/pyscf@v2.2.1 
RUN cd ../ 
RUN rm -r ./qs
