{{- if .Values.gateway.secrets.kafkaEuDe.createExternalSecret -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.gateway.secrets.kafkaEuDe.name }}
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - secretKey: credentials
    remoteRef:
      key: {{ .Values.gateway.secrets.kafkaEuDe.secretRef }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.gateway.secrets.kafkaEuDe.secretStoreName }}
  target:
    template:
      engineVersion: v2
      data:
        api_key: >-
          {{ printf "{{ (.credentials | fromJson).api_key }}" }}
        bootstrap_servers: >-
          {{ printf "{{ (.credentials | fromJson).kafka_brokers_sasl | join \",\" }}" }}
        user: >-
          {{ printf "{{ (.credentials | fromJson).user }}" }}
    creationPolicy: Owner
    name: {{ .Values.gateway.secrets.kafkaEuDe.name }}
{{- end -}}
