{{- if .Values.gateway.kafkaCredentials.create -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-credentials
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - secretKey: credentials
    remoteRef:
      key: "{{ .Values.gateway.secrets.kafka }}"
  secretStoreRef:
    kind: SecretStore
    name: qiskit-serverless-secret-store
  target:
    template:
      engineVersion: v2
      data:
        api_key: >-
          {{ printf "{{ (.credentials | fromJson).api_key }}" }}
        bootstrap_servers: >-
          {{ printf "{{ (.credentials | fromJson).kafka_brokers_sasl | join \",\" }}" }}
        user: >-
          {{ printf "{{ (.credentials | fromJson).user }}" }}
    creationPolicy: Owner
    name: kafka-credentials
{{- end -}}
