{{- if eq .Values.platform "kind" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.secrets.servicePsql.name }}
stringData:
  {{ .Values.gateway.secrets.servicePsql.key.databaseName }}: {{ .Values.gateway.secrets.servicePsql.value.databaseName }}
  {{ .Values.gateway.secrets.servicePsql.key.databasePassword }}: {{ .Values.gateway.secrets.servicePsql.value.databasePassword }}
  {{ .Values.gateway.secrets.servicePsql.key.host }}: {{ .Values.gateway.secrets.servicePsql.value.host }}
  {{ .Values.gateway.secrets.servicePsql.key.port }}: {{ .Values.gateway.secrets.servicePsql.value.port | quote }}
  {{ .Values.gateway.secrets.servicePsql.key.userName }}: {{ .Values.gateway.secrets.servicePsql.value.userName }}
{{- end }}
