{{- if eq .Values.platform "kind" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.secrets.secretKey.name }}
stringData:
  {{ .Values.gateway.secrets.secretKey.key }}: {{ .Values.gateway.secrets.secretKey.value }}
{{- end }}
