{{- if .Values.gateway.application.w3idSso.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-w3id-sso
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - secretKey: key_all
    remoteRef:
      key: "{{ .Values.gateway.secrets.w3idSso.name }}"
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.gateway.secrets.w3idSso.secretStoreName }}
  target:
    creationPolicy: Owner
    name: gateway-w3id-sso
{{- end -}}
