{{- if .Values.gateway.w3idSsoCredentials.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-w3id-sso
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - secretKey: credentials
    remoteRef:
      key: "{{ .Values.gateway.secrets.w3idSso }}"
  secretStoreRef:
    kind: SecretStore
    name: qiskit-serverless-secret-store
  target:
    template:
      engineVersion: v2
      data:
        client-id: >-
          {{ printf "{{ (.credentials | fromJson).client_id }}" }}
        client-secret: >-
          {{ printf "{{ (.credentials | fromJson).client_secret }}" }}
    creationPolicy: Owner
    name: gateway-w3id-sso
{{- end -}}
