{{- if .Values.gateway.application.w3idSso.enabled -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.gateway.secrets.w3idSso.name }}
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - secretKey: key_all
    remoteRef:
      key: {{ .Values.gateway.secrets.w3idSso.secretRef }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.gateway.secrets.w3idSso.secretStoreName }}
  target:
    creationPolicy: Owner
    name: {{ .Values.gateway.secrets.w3idSso.name }}
{{- end -}}
