site_name: 'VT Middleware'
site_description: 'VT Middleware'

repo_url: https://github.ibm.com/IBM-Q-Software/qiskit-serverless/
edit_uri: edit/master/techdocs/middleware/docs/

nav:
  - index.md

plugins:
  - techdocs-core