# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2GPUPreference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"allocation": "str", "family": "str"}

    attribute_map = {"allocation": "allocation", "family": "family"}

    def __init__(self, allocation=None, family=None):  # noqa: E501
        """V2GPUPreference - a model defined in Swagger"""  # noqa: E501
        self._allocation = None
        self._family = None
        self.discriminator = None
        self.allocation = allocation
        self.family = family

    @property
    def allocation(self):
        """Gets the allocation of this V2GPUPreference.  # noqa: E501

        The number of GPUs to be allocated per task instance.  # noqa: E501

        :return: The allocation of this V2GPUPreference.  # noqa: E501
        :rtype: str
        """
        return self._allocation

    @allocation.setter
    def allocation(self, allocation):
        """Sets the allocation of this V2GPUPreference.

        The number of GPUs to be allocated per task instance.  # noqa: E501

        :param allocation: The allocation of this V2GPUPreference.  # noqa: E501
        :type: str
        """
        if allocation is None:
            raise ValueError("Invalid value for `allocation`, must not be `None`")  # noqa: E501

        self._allocation = allocation

    @property
    def family(self):
        """Gets the family of this V2GPUPreference.  # noqa: E501

        The name of the GPU family.  # noqa: E501

        :return: The family of this V2GPUPreference.  # noqa: E501
        :rtype: str
        """
        return self._family

    @family.setter
    def family(self, family):
        """Sets the family of this V2GPUPreference.

        The name of the GPU family.  # noqa: E501

        :param family: The family of this V2GPUPreference.  # noqa: E501
        :type: str
        """
        if family is None:
            raise ValueError("Invalid value for `family`, must not be `None`")  # noqa: E501

        self._family = family

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2GPUPreference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2GPUPreference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
