# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2Project(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.

    The gateway reads ``name``, ``region`` and ``status`` to pick the right project,
    then ``id`` and ``resource_group_id`` from it, so those five carry the feature.
    ``account_id``, ``crn``, ``created_at``, ``href`` and ``resource_type`` are kept
    because they cost nothing and make a logged project recognisable. Setters do not
    reject ``None`` so a response missing an unused field still deserializes.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "account_id": "str",
        "created_at": "datetime",
        "crn": "str",
        "href": "str",
        "id": "str",
        "name": "str",
        "region": "str",
        "resource_group_id": "str",
        "resource_type": "str",
        "status": "str",
    }

    attribute_map = {
        "account_id": "account_id",
        "created_at": "created_at",
        "crn": "crn",
        "href": "href",
        "id": "id",
        "name": "name",
        "region": "region",
        "resource_group_id": "resource_group_id",
        "resource_type": "resource_type",
        "status": "status",
    }

    def __init__(
        self,
        account_id=None,
        created_at=None,
        crn=None,
        href=None,
        id=None,
        name=None,
        region=None,
        resource_group_id=None,
        resource_type=None,
        status=None,
    ):  # noqa: E501
        """V2Project - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._created_at = None
        self._crn = None
        self._href = None
        self._id = None
        self._name = None
        self._region = None
        self._resource_group_id = None
        self._resource_type = None
        self._status = None
        self.discriminator = None
        self.account_id = account_id
        self.created_at = created_at
        self.crn = crn
        self.href = href
        self.id = id
        self.name = name
        self.region = region
        self.resource_group_id = resource_group_id
        self.resource_type = resource_type
        self.status = status

    @property
    def account_id(self):
        """Gets the account_id of this V2Project.  # noqa: E501

        :return: The account_id of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this V2Project.

        :param account_id: The account_id of this V2Project.  # noqa: E501
        :type: str
        """
        self._account_id = account_id

    @property
    def created_at(self):
        """Gets the created_at of this V2Project.  # noqa: E501

        :return: The created_at of this V2Project.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this V2Project.

        :param created_at: The created_at of this V2Project.  # noqa: E501
        :type: datetime
        """
        self._created_at = created_at

    @property
    def crn(self):
        """Gets the crn of this V2Project.  # noqa: E501

        :return: The crn of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._crn

    @crn.setter
    def crn(self, crn):
        """Sets the crn of this V2Project.

        :param crn: The crn of this V2Project.  # noqa: E501
        :type: str
        """
        self._crn = crn

    @property
    def href(self):
        """Gets the href of this V2Project.  # noqa: E501

        :return: The href of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V2Project.

        :param href: The href of this V2Project.  # noqa: E501
        :type: str
        """
        self._href = href

    @property
    def id(self):
        """Gets the id of this V2Project.  # noqa: E501

        :return: The id of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2Project.

        :param id: The id of this V2Project.  # noqa: E501
        :type: str
        """
        self._id = id

    @property
    def name(self):
        """Gets the name of this V2Project.  # noqa: E501

        :return: The name of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2Project.

        :param name: The name of this V2Project.  # noqa: E501
        :type: str
        """
        self._name = name

    @property
    def region(self):
        """Gets the region of this V2Project.  # noqa: E501

        :return: The region of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this V2Project.

        :param region: The region of this V2Project.  # noqa: E501
        :type: str
        """
        self._region = region

    @property
    def resource_group_id(self):
        """Gets the resource_group_id of this V2Project.  # noqa: E501

        :return: The resource_group_id of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._resource_group_id

    @resource_group_id.setter
    def resource_group_id(self, resource_group_id):
        """Sets the resource_group_id of this V2Project.

        :param resource_group_id: The resource_group_id of this V2Project.  # noqa: E501
        :type: str
        """
        self._resource_group_id = resource_group_id

    @property
    def resource_type(self):
        """Gets the resource_type of this V2Project.  # noqa: E501

        :return: The resource_type of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this V2Project.

        :param resource_type: The resource_type of this V2Project.  # noqa: E501
        :type: str
        """
        self._resource_type = resource_type

    @property
    def status(self):
        """Gets the status of this V2Project.  # noqa: E501

        :return: The status of this V2Project.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V2Project.

        :param status: The status of this V2Project.  # noqa: E501
        :type: str
        """
        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2Project, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2Project):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
