# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2SubnetPool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.

    Altered from the original generated model: the ``pool`` field
    (``list[V2SubnetPoolReference]``) is dropped because the gateway only reads a
    pool's ``id``, ``name`` and ``region`` to resolve a configured pool name, and
    keeping it would pull in the ``V2SubnetPoolReference`` model for no benefit.
    Setters do not reject ``None`` so a response missing an unused field still
    deserializes.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "created_at": "datetime",
        "href": "str",
        "id": "str",
        "name": "str",
        "project_id": "str",
        "region": "str",
        "resource_type": "str",
    }

    attribute_map = {
        "created_at": "created_at",
        "href": "href",
        "id": "id",
        "name": "name",
        "project_id": "project_id",
        "region": "region",
        "resource_type": "resource_type",
    }

    def __init__(
        self,
        created_at=None,
        href=None,
        id=None,
        name=None,
        project_id=None,
        region=None,
        resource_type=None,
    ):  # noqa: E501
        """V2SubnetPool - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._href = None
        self._id = None
        self._name = None
        self._project_id = None
        self._region = None
        self._resource_type = None
        self.discriminator = None
        self.created_at = created_at
        self.href = href
        self.id = id
        self.name = name
        self.project_id = project_id
        self.region = region
        self.resource_type = resource_type

    @property
    def created_at(self):
        """Gets the created_at of this V2SubnetPool.  # noqa: E501

        :return: The created_at of this V2SubnetPool.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this V2SubnetPool.

        :param created_at: The created_at of this V2SubnetPool.  # noqa: E501
        :type: datetime
        """
        self._created_at = created_at

    @property
    def href(self):
        """Gets the href of this V2SubnetPool.  # noqa: E501

        :return: The href of this V2SubnetPool.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V2SubnetPool.

        :param href: The href of this V2SubnetPool.  # noqa: E501
        :type: str
        """
        self._href = href

    @property
    def id(self):
        """Gets the id of this V2SubnetPool.  # noqa: E501

        The identifier of the resource.  # noqa: E501

        :return: The id of this V2SubnetPool.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2SubnetPool.

        The identifier of the resource.  # noqa: E501

        :param id: The id of this V2SubnetPool.  # noqa: E501
        :type: str
        """
        self._id = id

    @property
    def name(self):
        """Gets the name of this V2SubnetPool.  # noqa: E501

        The name of the subnet pool.  # noqa: E501

        :return: The name of this V2SubnetPool.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2SubnetPool.

        The name of the subnet pool.  # noqa: E501

        :param name: The name of this V2SubnetPool.  # noqa: E501
        :type: str
        """
        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this V2SubnetPool.  # noqa: E501

        The ID of the project in which the resource is located.  # noqa: E501

        :return: The project_id of this V2SubnetPool.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this V2SubnetPool.

        The ID of the project in which the resource is located.  # noqa: E501

        :param project_id: The project_id of this V2SubnetPool.  # noqa: E501
        :type: str
        """
        self._project_id = project_id

    @property
    def region(self):
        """Gets the region of this V2SubnetPool.  # noqa: E501

        The region of the project the resource is located in.  # noqa: E501

        :return: The region of this V2SubnetPool.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this V2SubnetPool.

        The region of the project the resource is located in.  # noqa: E501

        :param region: The region of this V2SubnetPool.  # noqa: E501
        :type: str
        """
        self._region = region

    @property
    def resource_type(self):
        """Gets the resource_type of this V2SubnetPool.  # noqa: E501

        The type of the subnet pool.  # noqa: E501

        :return: The resource_type of this V2SubnetPool.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this V2SubnetPool.

        The type of the subnet pool.  # noqa: E501

        :param resource_type: The resource_type of this V2SubnetPool.  # noqa: E501
        :type: str
        """
        self._resource_type = resource_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2SubnetPool, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2SubnetPool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
