{{- if .Values.secrets.secretKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretKey.name  }}
stringData:
  {{ .Values.secrets.secretKey.key }}: {{ .Values.secrets.secretKey.value }}
{{ end }}
