name: Helm lint
description: Action to lint and validate helm configuration

runs:
  using: composite
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0  #4.2.0
      with:
        version: v3.12.1

    # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
    # yamllint (https://github.com/adrienverge/yamllint) which require Python
    - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f #5.1.1
      with:
        python-version: '3.10'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 #2.6.1

    - name: Run chart-testing (list-changed)
      shell: bash
      id: list-changed
      run: |
        changed=$(ct list-changed --config ct.yaml)
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      shell: bash
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --config ct.yaml --check-version-increment=false

    # - name: Create kind cluster
    #   if: steps.list-changed.outputs.changed == 'true'
    #   uses: helm/kind-action@v1.7.0

    # - name: Run chart-testing (install)
    #   shell: bash
    #   if: steps.list-changed.outputs.changed == 'true'
    #   run: ct install --config ct.yaml
