apiVersion: v2
name: qs-observability
description: Quantum-Serverless helm chart for observabililty (i.e. logging/monitoring).

type: application

version: 0.6.1
appVersion: "0.6.1"

dependencies:
  - name: kube-prometheus-stack
    condition: prometheusEnable
    version: 45.31.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    condition: lokiEnable
    version: 4.10.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    condition: promtailEnable
    version: 6.14.1
    repository: https://grafana.github.io/helm-charts

maintainers:
  - name: akihikokuroda
  - name: IceKhan13
  - name: psschwei
  - name: Tansito
