# ===================
# Quantum Serverless Observability configs
# ===================


# ===================
# Prometheus
# ===================

prometheusEnable: true
kube-prometheus-stack:
  nameOverride: "prometheus"
  fullnameOverride: "prometheus"

  kube-state-metrics:
    nameOverride: "kube-state-metrics"
    fullnameOverride: "kube-state-metrics"

  prometheus-node-exporter:
    nameOverride: "prometheus-node-exporter"
    fullnameOverride: "prometheus-node-exporter"

  grafana:
    nameOverride: "grafana"
    fullnameOverride: "grafana"

    adminPassword: passw0rd

# ===================
# loki
# ===================

lokiEnable: true
loki:
  nameOverride: "loki"
  fullnameOverride: "loki"

  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
    auth_enabled: false
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  singleBinary:
    replicas: 1
  gateway:
    service:
      type: ClusterIP
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
  test:
    enabled: false

# ===================
# promtail
# ===================

promtailEnable: true
promtail:
  nameOverride: "promtail"
  fullnameOverride: "promtail"
