# ===================
# Quantum Serverless Observability configs
# ===================


# ===================
# Prometheus
# ===================

prometheusEnable: true
kube-prometheus-stack:
  nameOverride: "prometheus"
  fullnameOverride: "prometheus"

  kube-state-metrics:
    nameOverride: "kube-state-metrics"
    fullnameOverride: "kube-state-metrics"

  prometheus-node-exporter:
    nameOverride: "prometheus-node-exporter"
    fullnameOverride: "prometheus-node-exporter"

  grafana:
    nameOverride: "grafana"
    fullnameOverride: "grafana"

    adminPassword: passw0rd

    # Keycloak Sign-on for Grafana console
    #
    # To enable sign-on by Keycloak for Grafana console
    # 1. replace <Non-Loopback local IP> with the local IP address
    # 2. change the keycloak service to NodePort type and add
    #    nodePorts
    #      http: 32059
    # 3. uncomment following lines
    #
    # service:
    #  type: NodePort
    #  nodePort: 32294
    # grafana.ini:
    #  auth:
    #    disable_login_form: "true"
    #  auth.generic_oauth:
    #    enabled: "true"
    #    name: Keycloak-OAuth
    #    allow_sign_up: "true"
    #    client_id: grafana-client
    #    client_secret: GRAFANASECRET-CHANGEME
    #    api_url: "http://<Non-Loopback local IP>:31059/realms/quantum-serverless/protocol/openid-connect/userinfo"
    #    auth_url: "http://<Non-Loopback local IP>:31059/realms/quantum-serverless/protocol/openid-connect/auth"
    #    token_url: "http://<Non-Loopback local IP>:31059/realms/quantum-serverless/protocol/openid-connect/token"
    #    role_attribute_path: "contains(roles[*], 'grafana-admin') && 'GrafanaAdmin' || contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"
    #    allow_assign_grafana_admin: "true"
    #    scopes: openid email profile roles
    #    email_attribute_path: user@quatunserverless.org
    #    login_attribute_path: user
    #    name_attribute_path: none
    #  log:
    #    level: debug
    #  server:
    #    root_url: "http://localhost:32294/"

# ===================
# loki
# ===================

lokiEnable: true
loki:
  nameOverride: "loki"
  fullnameOverride: "loki"

  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
    auth_enabled: false
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  singleBinary:
    replicas: 1
  gateway:
    service:
      type: ClusterIP
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
  test:
    enabled: false

# ===================
# promtail
# ===================

promtailEnable: true
promtail:
  nameOverride: "promtail"
  fullnameOverride: "promtail"
