FROM icr.io/quantum-public/qiskit-serverless-ray-node:0.11.0-py310

# install all necessary dependencies for your custom image

# copy our function implementation in `/runner.py` of the docker image
RUN mkdir /runner
COPY ./runner.py /runner/runner.py
