{
 "title": "Gateway",
 "description": "Gateay Django metrics dashboard using django-prometheus metrics exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(django_http_requests_total_by_transport_total,kube_deployment_name)"
    }
   },
   {
    "name": "threshold",
    "label": "threshold",
    "query": "100ms : 0.1, 250ms : 0.25, 500ms : 0.5, 750ms : 0.75, 1s : 1.0, 2.5s : 2.5, 5s : 5.0, 7.5s : 7.5, 10s : 10.0, 25s : 25.0"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",kube_deployment_name=~\"^$application$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\",kube_deployment_name=~\"^$application$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "DB Query Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(django_db_errors_total{kube_deployment_name=~\"^$application$\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connection Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(django_db_new_connection_errors_total{kube_deployment_name=~\"^$application$\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Queries per HTTP Request",
   "type": "stat",
   "description": "Average number of database executions triggered by each incoming HTTP request",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_db_execute_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (kube_deployment_name)\n/\nsum(rate(django_http_requests_total_by_transport_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (kube_deployment_name)",
     "legendFormat": "DB queries / request"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"3.+\",kube_deployment_name=~\"^$application$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\",kube_deployment_name=~\"^$application$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Number of Requests by Processing Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of Responses by Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_body_total_bytes_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (le))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 quantile"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top 20 Views by Response Time (> $threshold)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20, (1 - (sum(max_over_time(django_http_requests_latency_seconds_by_view_method_bucket{kube_deployment_name=~\"^$application$\",le=\"$threshold\"}[$__range]) / ignoring(le) max_over_time(django_http_requests_latency_seconds_by_view_method_count{kube_deployment_name=~\"^$application$\"}[$__range])) by (method, view) / count(present_over_time(django_http_requests_latency_seconds_by_view_method_count{kube_deployment_name=~\"^$application$\"}[$__range])) by (method, view))) > 0.0099 and on(view)(django_http_requests_latency_seconds_by_view_method_count{view=~\"v1:.*\"}))",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(django_http_requests_total_by_view_transport_method_total{kube_deployment_name=~\"^$application$\",view!~\"prometheus-django-metrics|healthcheck|liveness|readiness\"}[$__rate_interval])) by(method, view) > 0)",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Query Rate by alias",
     "type": "timeseries",
     "description": "Rate of database statements executed per second, by database alias.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (alias) (irate(django_db_execute_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum by (alias) (irate(django_db_execute_many_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval]))",
       "legendFormat": "{{alias}} (executemany)"
      }
     ]
    },
    {
     "title": "DB Query Duration Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(django_db_query_duration_seconds_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "DB Query Duration Percentiles (p50 / p95 / p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (alias, le) (rate(django_db_query_duration_seconds_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])))",
       "legendFormat": "p50 {{alias}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (alias, le) (rate(django_db_query_duration_seconds_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])))",
       "legendFormat": "p95 {{alias}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (alias, le) (rate(django_db_query_duration_seconds_bucket{kube_deployment_name=~\"^$application$\"}[$__rate_interval])))",
       "legendFormat": "p99 {{alias}}"
      }
     ]
    },
    {
     "title": "DB New Connections Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (alias) (irate(django_db_new_connections_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval]))",
       "legendFormat": "new connections {{alias}}"
      }
     ]
    },
    {
     "title": "DB Error Rate over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum by (alias) (irate(django_db_errors_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval]))",
       "legendFormat": "query errors {{alias}}"
      },
      {
       "expr": "sum by (alias) (irate(django_db_new_connection_errors_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval]))",
       "legendFormat": "connection errors {{alias}}"
      }
     ]
    },
    {
     "title": "Model Operations (inserts / updates / deletes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(django_model_inserts_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (model)",
       "legendFormat": "inserts {{model}}"
      },
      {
       "expr": "sum(irate(django_model_updates_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (model)",
       "legendFormat": "updates {{model}}"
      },
      {
       "expr": "sum(irate(django_model_deletes_total{kube_deployment_name=~\"^$application$\"}[$__rate_interval])) by (model)",
       "legendFormat": "deletes {{model}}"
      }
     ]
    }
   ]
  }
 ]
}