# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class FleetsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def cancel_fleet(self, project_id, id, **kwargs):  # noqa: E501
        """Cancel a fleet  # noqa: E501

        Cancel a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.cancel_fleet(project_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str id: The ID of the fleet. (required)
        :param V2FleetCancel body: Fleet cancel request.
        :return: V2Fleet
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.cancel_fleet_with_http_info(project_id, id, **kwargs)  # noqa: E501
        else:
            data = self.cancel_fleet_with_http_info(project_id, id, **kwargs)  # noqa: E501
            return data

    def cancel_fleet_with_http_info(self, project_id, id, **kwargs):  # noqa: E501
        """Cancel a fleet  # noqa: E501

        Cancel a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.cancel_fleet_with_http_info(project_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str id: The ID of the fleet. (required)
        :param V2FleetCancel body: Fleet cancel request.
        :return: V2Fleet
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "id", "body"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method cancel_fleet" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `cancel_fleet`")  # noqa: E501
        # verify the required parameter 'id' is set
        if "id" not in params or params["id"] is None:
            raise ValueError("Missing the required parameter `id` when calling `cancel_fleet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "id" in params:
            path_params["id"] = params["id"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{id}/cancel",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Fleet",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def create_fleet(self, body, project_id, **kwargs):  # noqa: E501
        """Create a fleet  # noqa: E501

        Create a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_fleet(body, project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2FleetPrototype body: Fleet prototype. (required)
        :param str project_id: The ID of the project. (required)
        :return: V2Fleet
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.create_fleet_with_http_info(body, project_id, **kwargs)  # noqa: E501
        else:
            data = self.create_fleet_with_http_info(body, project_id, **kwargs)  # noqa: E501
            return data

    def create_fleet_with_http_info(self, body, project_id, **kwargs):  # noqa: E501
        """Create a fleet  # noqa: E501

        Create a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_fleet_with_http_info(body, project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2FleetPrototype body: Fleet prototype. (required)
        :param str project_id: The ID of the project. (required)
        :return: V2Fleet
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["body", "project_id"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method create_fleet" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'body' is set
        if "body" not in params or params["body"] is None:
            raise ValueError("Missing the required parameter `body` when calling `create_fleet`")  # noqa: E501
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `create_fleet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Fleet",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def delete_fleet(self, project_id, id, **kwargs):  # noqa: E501
        """Delete a fleet  # noqa: E501

        Delete a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_fleet(project_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str id: The ID of the fleet. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.delete_fleet_with_http_info(project_id, id, **kwargs)  # noqa: E501
        else:
            data = self.delete_fleet_with_http_info(project_id, id, **kwargs)  # noqa: E501
            return data

    def delete_fleet_with_http_info(self, project_id, id, **kwargs):  # noqa: E501
        """Delete a fleet  # noqa: E501

        Delete a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_fleet_with_http_info(project_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str id: The ID of the fleet. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "id"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method delete_fleet" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `delete_fleet`")  # noqa: E501
        # verify the required parameter 'id' is set
        if "id" not in params or params["id"] is None:
            raise ValueError("Missing the required parameter `id` when calling `delete_fleet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "id" in params:
            path_params["id"] = params["id"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{id}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_fleet(self, project_id, id, **kwargs):  # noqa: E501
        """Get a fleet  # noqa: E501

        Get a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_fleet(project_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str id: The ID of the fleet. (required)
        :return: V2Fleet
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_fleet_with_http_info(project_id, id, **kwargs)  # noqa: E501
        else:
            data = self.get_fleet_with_http_info(project_id, id, **kwargs)  # noqa: E501
            return data

    def get_fleet_with_http_info(self, project_id, id, **kwargs):  # noqa: E501
        """Get a fleet  # noqa: E501

        Get a fleet.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_fleet_with_http_info(project_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str id: The ID of the fleet. (required)
        :return: V2Fleet
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "id"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method get_fleet" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `get_fleet`")  # noqa: E501
        # verify the required parameter 'id' is set
        if "id" not in params or params["id"] is None:
            raise ValueError("Missing the required parameter `id` when calling `get_fleet`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "id" in params:
            path_params["id"] = params["id"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{id}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Fleet",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_fleet_task(self, project_id, fleet_id, id, **kwargs):  # noqa: E501
        """Get a task  # noqa: E501

        Get a task.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_fleet_task(project_id, fleet_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :param str id: The ID of the task. (required)
        :return: V2Task
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_fleet_task_with_http_info(project_id, fleet_id, id, **kwargs)  # noqa: E501
        else:
            data = self.get_fleet_task_with_http_info(project_id, fleet_id, id, **kwargs)  # noqa: E501
            return data

    def get_fleet_task_with_http_info(self, project_id, fleet_id, id, **kwargs):  # noqa: E501
        """Get a task  # noqa: E501

        Get a task.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_fleet_task_with_http_info(project_id, fleet_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :param str id: The ID of the task. (required)
        :return: V2Task
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "fleet_id", "id"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method get_fleet_task" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `get_fleet_task`")  # noqa: E501
        # verify the required parameter 'fleet_id' is set
        if "fleet_id" not in params or params["fleet_id"] is None:
            raise ValueError("Missing the required parameter `fleet_id` when calling `get_fleet_task`")  # noqa: E501
        # verify the required parameter 'id' is set
        if "id" not in params or params["id"] is None:
            raise ValueError("Missing the required parameter `id` when calling `get_fleet_task`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "fleet_id" in params:
            path_params["fleet_id"] = params["fleet_id"]  # noqa: E501
        if "id" in params:
            path_params["id"] = params["id"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{fleet_id}/tasks/{id}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Task",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_fleet_worker(self, project_id, fleet_id, name, **kwargs):  # noqa: E501
        """Get a worker  # noqa: E501

        Get a worker.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_fleet_worker(project_id, fleet_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :param str name: The name of the worker. (required)
        :return: V2Worker
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_fleet_worker_with_http_info(project_id, fleet_id, name, **kwargs)  # noqa: E501
        else:
            data = self.get_fleet_worker_with_http_info(project_id, fleet_id, name, **kwargs)  # noqa: E501
            return data

    def get_fleet_worker_with_http_info(self, project_id, fleet_id, name, **kwargs):  # noqa: E501
        """Get a worker  # noqa: E501

        Get a worker.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_fleet_worker_with_http_info(project_id, fleet_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :param str name: The name of the worker. (required)
        :return: V2Worker
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "fleet_id", "name"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method get_fleet_worker" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `get_fleet_worker`"
            )  # noqa: E501
        # verify the required parameter 'fleet_id' is set
        if "fleet_id" not in params or params["fleet_id"] is None:
            raise ValueError("Missing the required parameter `fleet_id` when calling `get_fleet_worker`")  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `get_fleet_worker`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "fleet_id" in params:
            path_params["fleet_id"] = params["fleet_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{fleet_id}/workers/{name}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Worker",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_fleet_tasks(self, project_id, fleet_id, **kwargs):  # noqa: E501
        """List tasks  # noqa: E501

        List tasks.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleet_tasks(project_id, fleet_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :param str status: Status condition to filter the tasks by
        :param int limit: Optional maximum number of subnet pools per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2TaskList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_fleet_tasks_with_http_info(project_id, fleet_id, **kwargs)  # noqa: E501
        else:
            data = self.list_fleet_tasks_with_http_info(project_id, fleet_id, **kwargs)  # noqa: E501
            return data

    def list_fleet_tasks_with_http_info(self, project_id, fleet_id, **kwargs):  # noqa: E501
        """List tasks  # noqa: E501

        List tasks.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleet_tasks_with_http_info(project_id, fleet_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :param str status: Status condition to filter the tasks by
        :param int limit: Optional maximum number of subnet pools per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2TaskList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "fleet_id", "status", "limit", "start"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method list_fleet_tasks" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `list_fleet_tasks`"
            )  # noqa: E501
        # verify the required parameter 'fleet_id' is set
        if "fleet_id" not in params or params["fleet_id"] is None:
            raise ValueError("Missing the required parameter `fleet_id` when calling `list_fleet_tasks`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "fleet_id" in params:
            path_params["fleet_id"] = params["fleet_id"]  # noqa: E501

        query_params = []
        if "status" in params:
            query_params.append(("status", params["status"]))  # noqa: E501
        if "limit" in params:
            query_params.append(("limit", params["limit"]))  # noqa: E501
        if "start" in params:
            query_params.append(("start", params["start"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{fleet_id}/tasks",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2TaskList",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_fleet_worker_profiles(self, **kwargs):  # noqa: E501
        """List available worker profiles  # noqa: E501

        List available worker profiles.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleet_worker_profiles(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: V2WorkerProfileList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_fleet_worker_profiles_with_http_info(**kwargs)  # noqa: E501
        else:
            data = self.list_fleet_worker_profiles_with_http_info(**kwargs)  # noqa: E501
            return data

    def list_fleet_worker_profiles_with_http_info(self, **kwargs):  # noqa: E501
        """List available worker profiles  # noqa: E501

        List available worker profiles.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleet_worker_profiles_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: V2WorkerProfileList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method list_fleet_worker_profiles" % key)
            params[key] = val
        del params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/worker_profiles",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2WorkerProfileList",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_fleet_workers(self, project_id, fleet_id, **kwargs):  # noqa: E501
        """List workers  # noqa: E501

        List workers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleet_workers(project_id, fleet_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :return: V2WorkerList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_fleet_workers_with_http_info(project_id, fleet_id, **kwargs)  # noqa: E501
        else:
            data = self.list_fleet_workers_with_http_info(project_id, fleet_id, **kwargs)  # noqa: E501
            return data

    def list_fleet_workers_with_http_info(self, project_id, fleet_id, **kwargs):  # noqa: E501
        """List workers  # noqa: E501

        List workers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleet_workers_with_http_info(project_id, fleet_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str fleet_id: The ID of the fleet. (required)
        :return: V2WorkerList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "fleet_id"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method list_fleet_workers" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `list_fleet_workers`"
            )  # noqa: E501
        # verify the required parameter 'fleet_id' is set
        if "fleet_id" not in params or params["fleet_id"] is None:
            raise ValueError(
                "Missing the required parameter `fleet_id` when calling `list_fleet_workers`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "fleet_id" in params:
            path_params["fleet_id"] = params["fleet_id"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets/{fleet_id}/workers",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2WorkerList",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_fleets(self, project_id, **kwargs):  # noqa: E501
        """List fleets  # noqa: E501

        List all fleets in a project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleets(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param int limit: Optional maximum number of fleets per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2FleetList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_fleets_with_http_info(project_id, **kwargs)  # noqa: E501
        else:
            data = self.list_fleets_with_http_info(project_id, **kwargs)  # noqa: E501
            return data

    def list_fleets_with_http_info(self, project_id, **kwargs):  # noqa: E501
        """List fleets  # noqa: E501

        List all fleets in a project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_fleets_with_http_info(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param int limit: Optional maximum number of fleets per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2FleetList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "limit", "start"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method list_fleets" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `list_fleets`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501

        query_params = []
        if "limit" in params:
            query_params.append(("limit", params["limit"]))  # noqa: E501
        if "start" in params:
            query_params.append(("start", params["start"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/fleets",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2FleetList",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
