# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SecretsAndConfigmapsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_config_map(self, body, project_id, **kwargs):  # noqa: E501
        """Create a config map  # noqa: E501

        Create a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_config_map(body, project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2ConfigMapPrototype body: Config map prototype. (required)
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2ConfigMap
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.create_config_map_with_http_info(body, project_id, **kwargs)  # noqa: E501
        else:
            data = self.create_config_map_with_http_info(body, project_id, **kwargs)  # noqa: E501
            return data

    def create_config_map_with_http_info(self, body, project_id, **kwargs):  # noqa: E501
        """Create a config map  # noqa: E501

        Create a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_config_map_with_http_info(body, project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2ConfigMapPrototype body: Config map prototype. (required)
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2ConfigMap
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["body", "project_id", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method create_config_map" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'body' is set
        if "body" not in params or params["body"] is None:
            raise ValueError("Missing the required parameter `body` when calling `create_config_map`")  # noqa: E501
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `create_config_map`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/config_maps",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2ConfigMap",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def create_secret(self, body, project_id, **kwargs):  # noqa: E501
        """Create a secret  # noqa: E501

        Create a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_secret(body, project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2SecretPrototype body: Secret prototype. (required)
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2Secret
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.create_secret_with_http_info(body, project_id, **kwargs)  # noqa: E501
        else:
            data = self.create_secret_with_http_info(body, project_id, **kwargs)  # noqa: E501
            return data

    def create_secret_with_http_info(self, body, project_id, **kwargs):  # noqa: E501
        """Create a secret  # noqa: E501

        Create a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_secret_with_http_info(body, project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2SecretPrototype body: Secret prototype. (required)
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2Secret
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["body", "project_id", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method create_secret" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'body' is set
        if "body" not in params or params["body"] is None:
            raise ValueError("Missing the required parameter `body` when calling `create_secret`")  # noqa: E501
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `create_secret`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/secrets",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Secret",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def delete_config_map(self, project_id, name, **kwargs):  # noqa: E501
        """Delete a config map  # noqa: E501

        Delete a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_config_map(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your configmap. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.delete_config_map_with_http_info(project_id, name, **kwargs)  # noqa: E501
        else:
            data = self.delete_config_map_with_http_info(project_id, name, **kwargs)  # noqa: E501
            return data

    def delete_config_map_with_http_info(self, project_id, name, **kwargs):  # noqa: E501
        """Delete a config map  # noqa: E501

        Delete a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_config_map_with_http_info(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your configmap. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "name", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method delete_config_map" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `delete_config_map`"
            )  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `delete_config_map`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/config_maps/{name}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def delete_secret(self, project_id, name, **kwargs):  # noqa: E501
        """Delete a secret  # noqa: E501

        Delete a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_secret(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your secret. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.delete_secret_with_http_info(project_id, name, **kwargs)  # noqa: E501
        else:
            data = self.delete_secret_with_http_info(project_id, name, **kwargs)  # noqa: E501
            return data

    def delete_secret_with_http_info(self, project_id, name, **kwargs):  # noqa: E501
        """Delete a secret  # noqa: E501

        Delete a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_secret_with_http_info(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your secret. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "name", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method delete_secret" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `delete_secret`")  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `delete_secret`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/secrets/{name}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_config_map(self, project_id, name, **kwargs):  # noqa: E501
        """Get a config map  # noqa: E501

        Display the details of a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_config_map(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your configmap. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2ConfigMap
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_config_map_with_http_info(project_id, name, **kwargs)  # noqa: E501
        else:
            data = self.get_config_map_with_http_info(project_id, name, **kwargs)  # noqa: E501
            return data

    def get_config_map_with_http_info(self, project_id, name, **kwargs):  # noqa: E501
        """Get a config map  # noqa: E501

        Display the details of a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_config_map_with_http_info(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your configmap. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2ConfigMap
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "name", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method get_config_map" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `get_config_map`")  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `get_config_map`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/config_maps/{name}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2ConfigMap",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_secret(self, project_id, name, **kwargs):  # noqa: E501
        """Get a secret  # noqa: E501

        Get a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_secret(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your secret. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2Secret
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_secret_with_http_info(project_id, name, **kwargs)  # noqa: E501
        else:
            data = self.get_secret_with_http_info(project_id, name, **kwargs)  # noqa: E501
            return data

    def get_secret_with_http_info(self, project_id, name, **kwargs):  # noqa: E501
        """Get a secret  # noqa: E501

        Get a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_secret_with_http_info(project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your secret. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2Secret
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "name", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method get_secret" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `get_secret`")  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `get_secret`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/secrets/{name}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Secret",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_config_maps(self, project_id, **kwargs):  # noqa: E501
        """List config maps  # noqa: E501

        List all config maps in a project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_config_maps(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :param int limit: Optional maximum number of config maps per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2ConfigMapList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_config_maps_with_http_info(project_id, **kwargs)  # noqa: E501
        else:
            data = self.list_config_maps_with_http_info(project_id, **kwargs)  # noqa: E501
            return data

    def list_config_maps_with_http_info(self, project_id, **kwargs):  # noqa: E501
        """List config maps  # noqa: E501

        List all config maps in a project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_config_maps_with_http_info(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :param int limit: Optional maximum number of config maps per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2ConfigMapList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "version", "limit", "start"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method list_config_maps" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `list_config_maps`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501
        if "limit" in params:
            query_params.append(("limit", params["limit"]))  # noqa: E501
        if "start" in params:
            query_params.append(("start", params["start"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/config_maps",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2ConfigMapList",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_secrets(self, project_id, **kwargs):  # noqa: E501
        """List secrets  # noqa: E501

        List all secrets in a project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_secrets(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :param str format: Secret format to filter results by.
        :param int limit: Optional maximum number of secrets per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2SecretList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_secrets_with_http_info(project_id, **kwargs)  # noqa: E501
        else:
            data = self.list_secrets_with_http_info(project_id, **kwargs)  # noqa: E501
            return data

    def list_secrets_with_http_info(self, project_id, **kwargs):  # noqa: E501
        """List secrets  # noqa: E501

        List all secrets in a project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_secrets_with_http_info(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: The ID of the project. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :param str format: Secret format to filter results by.
        :param int limit: Optional maximum number of secrets per page.
        :param str start: An optional token that indicates the beginning of the page of results to be returned. If omitted, the first page of results is returned. This value is obtained from the 'start' query parameter in the `next` object of the operation response.
        :return: V2SecretList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_id", "version", "format", "limit", "start"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method list_secrets" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `list_secrets`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501
        if "format" in params:
            query_params.append(("format", params["format"]))  # noqa: E501
        if "limit" in params:
            query_params.append(("limit", params["limit"]))  # noqa: E501
        if "start" in params:
            query_params.append(("start", params["start"]))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/secrets",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2SecretList",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def replace_config_map(self, body, if_match, project_id, name, **kwargs):  # noqa: E501
        """Update a config map  # noqa: E501

        Update a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.replace_config_map(body, if_match, project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2ConfigMapPatch body: Config map prototype. (required)
        :param str if_match: Version of the config map settings to be updated. Specify the version that you retrieved as entity_tag (ETag header) when reading the config map. This value helps identifying parallel usage of this API. Pass * to indicate to update any version available. This might result in stale updates. (required)
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your configmap. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2ConfigMap
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.replace_config_map_with_http_info(body, if_match, project_id, name, **kwargs)  # noqa: E501
        else:
            data = self.replace_config_map_with_http_info(body, if_match, project_id, name, **kwargs)  # noqa: E501
            return data

    def replace_config_map_with_http_info(self, body, if_match, project_id, name, **kwargs):  # noqa: E501
        """Update a config map  # noqa: E501

        Update a config map.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.replace_config_map_with_http_info(body, if_match, project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2ConfigMapPatch body: Config map prototype. (required)
        :param str if_match: Version of the config map settings to be updated. Specify the version that you retrieved as entity_tag (ETag header) when reading the config map. This value helps identifying parallel usage of this API. Pass * to indicate to update any version available. This might result in stale updates. (required)
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your configmap. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2ConfigMap
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["body", "if_match", "project_id", "name", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method replace_config_map" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'body' is set
        if "body" not in params or params["body"] is None:
            raise ValueError("Missing the required parameter `body` when calling `replace_config_map`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if "if_match" not in params or params["if_match"] is None:
            raise ValueError(
                "Missing the required parameter `if_match` when calling `replace_config_map`"
            )  # noqa: E501
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError(
                "Missing the required parameter `project_id` when calling `replace_config_map`"
            )  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `replace_config_map`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}
        if "if_match" in params:
            header_params["If-Match"] = params["if_match"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/config_maps/{name}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2ConfigMap",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def replace_secret(self, body, if_match, project_id, name, **kwargs):  # noqa: E501
        """Update a secret  # noqa: E501

        Update a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.replace_secret(body, if_match, project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2SecretPatch body: Secret patch. (required)
        :param str if_match: Version of the secret settings to be updated. Specify the version that you retrieved as entity_tag (ETag header) when reading the secret. This value helps identifying parallel usage of this API. Pass * to indicate to update any version available. This might result in stale updates. (required)
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your secret. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2Secret
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.replace_secret_with_http_info(body, if_match, project_id, name, **kwargs)  # noqa: E501
        else:
            data = self.replace_secret_with_http_info(body, if_match, project_id, name, **kwargs)  # noqa: E501
            return data

    def replace_secret_with_http_info(self, body, if_match, project_id, name, **kwargs):  # noqa: E501
        """Update a secret  # noqa: E501

        Update a secret.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.replace_secret_with_http_info(body, if_match, project_id, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param V2SecretPatch body: Secret patch. (required)
        :param str if_match: Version of the secret settings to be updated. Specify the version that you retrieved as entity_tag (ETag header) when reading the secret. This value helps identifying parallel usage of this API. Pass * to indicate to update any version available. This might result in stale updates. (required)
        :param str project_id: The ID of the project. (required)
        :param str name: The name of your secret. (required)
        :param str version: The API version, in format `YYYY-MM-DD`
        :return: V2Secret
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["body", "if_match", "project_id", "name", "version"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method replace_secret" % key)
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'body' is set
        if "body" not in params or params["body"] is None:
            raise ValueError("Missing the required parameter `body` when calling `replace_secret`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if "if_match" not in params or params["if_match"] is None:
            raise ValueError("Missing the required parameter `if_match` when calling `replace_secret`")  # noqa: E501
        # verify the required parameter 'project_id' is set
        if "project_id" not in params or params["project_id"] is None:
            raise ValueError("Missing the required parameter `project_id` when calling `replace_secret`")  # noqa: E501
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError("Missing the required parameter `name` when calling `replace_secret`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "project_id" in params:
            path_params["project_id"] = params["project_id"]  # noqa: E501
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501

        header_params = {}
        if "if_match" in params:
            header_params["If-Match"] = params["if_match"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["Bearer"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_id}/secrets/{name}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="V2Secret",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
