"""Constants."""


META_TOPIC: str = "execution-meta"

QS_EXECUTION_WORKLOAD_ID: str = "QS_EXECUTION_WORKLOAD_ID"
QS_EXECUTION_UID: str = "QS_EXECUTION_UID"

QS_EVENTS_REDIS_HOST: str = "QS_EVENTS_REDIS_HOST"
QS_EVENTS_REDIS_PORT: str = "QS_EVENTS_REDIS_PORT"
QS_EVENTS_REDIS_PASSWORD: str = "QS_EVENTS_REDIS_PASSWORD"
