# ===================
# Quantum Serverless configs
# ===================
platform: ibm

# ===================
# Ingress Nginx controller configs
# ===================

# Ingress Nginx controller is disabled by default to not affect cloud providers' controller configuration
nginxIngressControllerEnable: false
ingress:
  annotations:
    # For IBM Cloud the valid ingress class values are: public-iks-k8s-nginx and private-iks-k8s-nginx
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
  tls:
    - hosts:
        - "gateway.YOUR_INGRESS_PUBLIC_END_POINT"
      secretName: "YOUR-INGRESS-SECRET"
  hosts:
    - host: "gateway.YOUR_INGRESS_PUBLIC_END_POINT"
      paths:
      - path: /
        pathType: Prefix
        serviceName: "gateway"
        servicePort: 8000

# ===================
# Gateway configs
# ===================

gatewayEnable: true
gateway:
  nameOverride: "gateway"
  fullnameOverride: "gateway"

  image:
    pullPolicy: IfNotPresent
    tag: "0.2.0"
  application:
    siteHost: "http://gateway:8000"
    rayHost: "http://kuberay-head-svc:8265"
    auth:
      mechanism: "custom_token"
      token:
        url: "https://auth-dev.quantum-computing.ibm.com/api/users/loginWithToken"
        verificationUrl: "https://auth-dev.quantum-computing.ibm.com/api/users/me"
        verificationField: "ibmQNetwork"
    superuser:
      username: "admin"
      password: "passw0rd"
      email: "admin@examplemail.io"
    service:
      type: ClusterIP
      port: 8000
    ray:
      nodeImage: "icr.io/quantum-public/quantum-serverless-ray-node:0.2.0-py39"
    limits:
      maxJobsPerUser: 2
      maxComputeResources: 4
  database:
    name: gateway_db

# ===================
# Redis configs
# ===================

redisEnable: false

# ===================
# Jupyter configs
# ===================

jupyterEnable: false

# ===================
# Kuberay Operator
# ===================

kuberayOperatorEnable: true
kuberay-operator:
  image:
    repository: kuberay/operator
    tag: v0.5.0
    pullPolicy: IfNotPresent

# ===================
# Keycloak
# ===================

keycloakEnable: false

# ===================
# Quantum Repository
# ===================

repositoryEnable: false

# ===================
# Prometheus
# ===================

prometheusEnable: false

# ===================
# loki
# ===================

lokiEnable: false

# ===================
# promtail
# ===================

promtailEnable: false

# ===================
# COS
# ===================

cos:
  bucket: BUCKETNAME-CHANGEME
  endpoint: ENDPOINT-CHANGEME
  secretName: SECRETNAME-CHANGEME
  storageClassName: STORAGECLASSNAME-CHANGEME
  storageSize: 10Gi
