# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2EnvVar(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "key": "str",
        "name": "str",
        "prefix": "str",
        "reference": "str",
        "type": "str",
        "value": "str",
    }

    attribute_map = {
        "key": "key",
        "name": "name",
        "prefix": "prefix",
        "reference": "reference",
        "type": "type",
        "value": "value",
    }

    def __init__(
        self, key=None, name=None, prefix=None, reference=None, type="literal", value=None
    ):  # noqa: E501
        """V2EnvVar - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._name = None
        self._prefix = None
        self._reference = None
        self._type = None
        self._value = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if name is not None:
            self.name = name
        if prefix is not None:
            self.prefix = prefix
        if reference is not None:
            self.reference = reference
        self.type = type
        if value is not None:
            self.value = value

    @property
    def key(self):
        """Gets the key of this V2EnvVar.  # noqa: E501

        The key to reference as environment variable.  # noqa: E501

        :return: The key of this V2EnvVar.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this V2EnvVar.

        The key to reference as environment variable.  # noqa: E501

        :param key: The key of this V2EnvVar.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def name(self):
        """Gets the name of this V2EnvVar.  # noqa: E501

        The name of the environment variable.  # noqa: E501

        :return: The name of this V2EnvVar.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2EnvVar.

        The name of the environment variable.  # noqa: E501

        :param name: The name of this V2EnvVar.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def prefix(self):
        """Gets the prefix of this V2EnvVar.  # noqa: E501

        A prefix that can be added to all keys of a full secret or config map reference.  # noqa: E501

        :return: The prefix of this V2EnvVar.  # noqa: E501
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """Sets the prefix of this V2EnvVar.

        A prefix that can be added to all keys of a full secret or config map reference.  # noqa: E501

        :param prefix: The prefix of this V2EnvVar.  # noqa: E501
        :type: str
        """

        self._prefix = prefix

    @property
    def reference(self):
        """Gets the reference of this V2EnvVar.  # noqa: E501

        The name of the secret or config map.  # noqa: E501

        :return: The reference of this V2EnvVar.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this V2EnvVar.

        The name of the secret or config map.  # noqa: E501

        :param reference: The reference of this V2EnvVar.  # noqa: E501
        :type: str
        """

        self._reference = reference

    @property
    def type(self):
        """Gets the type of this V2EnvVar.  # noqa: E501

        Specify the type of the environment variable.  # noqa: E501

        :return: The type of this V2EnvVar.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V2EnvVar.

        Specify the type of the environment variable.  # noqa: E501

        :param type: The type of this V2EnvVar.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = [
            "literal",
            "config_map_key_reference",
            "config_map_full_reference",
            "secret_key_reference",
            "secret_full_reference",
        ]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}".format(  # noqa: E501
                    type, allowed_values
                )
            )

        self._type = type

    @property
    def value(self):
        """Gets the value of this V2EnvVar.  # noqa: E501

        The literal value of the environment variable.  # noqa: E501

        :return: The value of this V2EnvVar.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this V2EnvVar.

        The literal value of the environment variable.  # noqa: E501

        :param value: The value of this V2EnvVar.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2EnvVar, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2EnvVar):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
