# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2FleetVolumeMountPrototype(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"mount_path": "str", "read_only": "bool", "reference": "str", "sub_path": "str", "type": "str"}

    attribute_map = {
        "mount_path": "mount_path",
        "read_only": "read_only",
        "reference": "reference",
        "sub_path": "sub_path",
        "type": "type",
    }

    def __init__(self, mount_path=None, read_only=False, reference=None, sub_path=None, type=None):  # noqa: E501
        """V2FleetVolumeMountPrototype - a model defined in Swagger"""  # noqa: E501
        self._mount_path = None
        self._read_only = None
        self._reference = None
        self._sub_path = None
        self._type = None
        self.discriminator = None
        self.mount_path = mount_path
        if read_only is not None:
            self.read_only = read_only
        self.reference = reference
        if sub_path is not None:
            self.sub_path = sub_path
        self.type = type

    @property
    def mount_path(self):
        """Gets the mount_path of this V2FleetVolumeMountPrototype.  # noqa: E501

        The path that should be mounted.  # noqa: E501

        :return: The mount_path of this V2FleetVolumeMountPrototype.  # noqa: E501
        :rtype: str
        """
        return self._mount_path

    @mount_path.setter
    def mount_path(self, mount_path):
        """Sets the mount_path of this V2FleetVolumeMountPrototype.

        The path that should be mounted.  # noqa: E501

        :param mount_path: The mount_path of this V2FleetVolumeMountPrototype.  # noqa: E501
        :type: str
        """
        if mount_path is None:
            raise ValueError("Invalid value for `mount_path`, must not be `None`")  # noqa: E501

        self._mount_path = mount_path

    @property
    def read_only(self):
        """Gets the read_only of this V2FleetVolumeMountPrototype.  # noqa: E501

        Optional flag to specify if the volume mount is read only.  # noqa: E501

        :return: The read_only of this V2FleetVolumeMountPrototype.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this V2FleetVolumeMountPrototype.

        Optional flag to specify if the volume mount is read only.  # noqa: E501

        :param read_only: The read_only of this V2FleetVolumeMountPrototype.  # noqa: E501
        :type: bool
        """

        self._read_only = read_only

    @property
    def reference(self):
        """Gets the reference of this V2FleetVolumeMountPrototype.  # noqa: E501

        The name of the referenced persistent data store.  # noqa: E501

        :return: The reference of this V2FleetVolumeMountPrototype.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this V2FleetVolumeMountPrototype.

        The name of the referenced persistent data store.  # noqa: E501

        :param reference: The reference of this V2FleetVolumeMountPrototype.  # noqa: E501
        :type: str
        """
        if reference is None:
            raise ValueError("Invalid value for `reference`, must not be `None`")  # noqa: E501

        self._reference = reference

    @property
    def sub_path(self):
        """Gets the sub_path of this V2FleetVolumeMountPrototype.  # noqa: E501

        The path mounted at the mount path.  # noqa: E501

        :return: The sub_path of this V2FleetVolumeMountPrototype.  # noqa: E501
        :rtype: str
        """
        return self._sub_path

    @sub_path.setter
    def sub_path(self, sub_path):
        """Sets the sub_path of this V2FleetVolumeMountPrototype.

        The path mounted at the mount path.  # noqa: E501

        :param sub_path: The sub_path of this V2FleetVolumeMountPrototype.  # noqa: E501
        :type: str
        """

        self._sub_path = sub_path

    @property
    def type(self):
        """Gets the type of this V2FleetVolumeMountPrototype.  # noqa: E501

        Specify the type of the volume mount. Allowed types are: 'persistent_data_store'.  # noqa: E501

        :return: The type of this V2FleetVolumeMountPrototype.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V2FleetVolumeMountPrototype.

        Specify the type of the volume mount. Allowed types are: 'persistent_data_store'.  # noqa: E501

        :param type: The type of this V2FleetVolumeMountPrototype.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["persistent_data_store"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}".format(type, allowed_values)  # noqa: E501
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2FleetVolumeMountPrototype, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2FleetVolumeMountPrototype):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
