# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2FleetPrototype(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "image_reference": "str",
        "image_secret": "str",
        "name": "str",
        "network_placements": "list[V2NetworkPlacementPrototype]",
        "run_arguments": "list[str]",
        "run_commands": "list[str]",
        "run_env_variables": "list[V2EnvVarPrototype]",
        "run_volume_mounts": "list[V2FleetVolumeMountPrototype]",
        "scale_cpu_limit": "str",
        "scale_gpu": "V2GPUScalePrototype",
        "scale_max_execution_time": "str",
        "scale_max_instances": "int",
        "scale_memory_limit": "str",
        "scale_preferred_worker_profile": "str",
        "scale_retry_limit": "int",
        "tasks_specification": "V2TasksSpecificationPrototype",
        "tasks_state_store": "V2TaskStateStorePrototype",
    }

    attribute_map = {
        "image_reference": "image_reference",
        "image_secret": "image_secret",
        "name": "name",
        "network_placements": "network_placements",
        "run_arguments": "run_arguments",
        "run_commands": "run_commands",
        "run_env_variables": "run_env_variables",
        "run_volume_mounts": "run_volume_mounts",
        "scale_cpu_limit": "scale_cpu_limit",
        "scale_gpu": "scale_gpu",
        "scale_max_execution_time": "scale_max_execution_time",
        "scale_max_instances": "scale_max_instances",
        "scale_memory_limit": "scale_memory_limit",
        "scale_preferred_worker_profile": "scale_preferred_worker_profile",
        "scale_retry_limit": "scale_retry_limit",
        "tasks_specification": "tasks_specification",
        "tasks_state_store": "tasks_state_store",
    }

    def __init__(
        self,
        image_reference=None,
        image_secret=None,
        name=None,
        network_placements=None,
        run_arguments=None,
        run_commands=None,
        run_env_variables=None,
        run_volume_mounts=None,
        scale_cpu_limit=None,
        scale_gpu=None,
        scale_max_execution_time=None,
        scale_max_instances=1,
        scale_memory_limit=None,
        scale_preferred_worker_profile=None,
        scale_retry_limit=3,
        tasks_specification=None,
        tasks_state_store=None,
    ):  # noqa: E501
        """V2FleetPrototype - a model defined in Swagger"""  # noqa: E501
        self._image_reference = None
        self._image_secret = None
        self._name = None
        self._network_placements = None
        self._run_arguments = None
        self._run_commands = None
        self._run_env_variables = None
        self._run_volume_mounts = None
        self._scale_cpu_limit = None
        self._scale_gpu = None
        self._scale_max_execution_time = None
        self._scale_max_instances = None
        self._scale_memory_limit = None
        self._scale_preferred_worker_profile = None
        self._scale_retry_limit = None
        self._tasks_specification = None
        self._tasks_state_store = None
        self.discriminator = None
        self.image_reference = image_reference
        if image_secret is not None:
            self.image_secret = image_secret
        self.name = name
        self.network_placements = network_placements
        if run_arguments is not None:
            self.run_arguments = run_arguments
        if run_commands is not None:
            self.run_commands = run_commands
        if run_env_variables is not None:
            self.run_env_variables = run_env_variables
        if run_volume_mounts is not None:
            self.run_volume_mounts = run_volume_mounts
        self.scale_cpu_limit = scale_cpu_limit
        if scale_gpu is not None:
            self.scale_gpu = scale_gpu
        if scale_max_execution_time is not None:
            self.scale_max_execution_time = scale_max_execution_time
        self.scale_max_instances = scale_max_instances
        self.scale_memory_limit = scale_memory_limit
        if scale_preferred_worker_profile is not None:
            self.scale_preferred_worker_profile = scale_preferred_worker_profile
        if scale_retry_limit is not None:
            self.scale_retry_limit = scale_retry_limit
        self.tasks_specification = tasks_specification
        self.tasks_state_store = tasks_state_store

    @property
    def image_reference(self):
        """Gets the image_reference of this V2FleetPrototype.  # noqa: E501

        The name of the image that is used for this fleet.  # noqa: E501

        :return: The image_reference of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._image_reference

    @image_reference.setter
    def image_reference(self, image_reference):
        """Sets the image_reference of this V2FleetPrototype.

        The name of the image that is used for this fleet.  # noqa: E501

        :param image_reference: The image_reference of this V2FleetPrototype.  # noqa: E501
        :type: str
        """
        if image_reference is None:
            raise ValueError("Invalid value for `image_reference`, must not be `None`")  # noqa: E501

        self._image_reference = image_reference

    @property
    def image_secret(self):
        """Gets the image_secret of this V2FleetPrototype.  # noqa: E501

        Optional name of the image registry access secret. The image registry access secret is used to authenticate with a private registry when you download the container image. If the image reference points to a registry that requires authentication, the fleet will not be able to process tasks.  # noqa: E501

        :return: The image_secret of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._image_secret

    @image_secret.setter
    def image_secret(self, image_secret):
        """Sets the image_secret of this V2FleetPrototype.

        Optional name of the image registry access secret. The image registry access secret is used to authenticate with a private registry when you download the container image. If the image reference points to a registry that requires authentication, the fleet will not be able to process tasks.  # noqa: E501

        :param image_secret: The image_secret of this V2FleetPrototype.  # noqa: E501
        :type: str
        """

        self._image_secret = image_secret

    @property
    def name(self):
        """Gets the name of this V2FleetPrototype.  # noqa: E501

        The name of the fleet.  # noqa: E501

        :return: The name of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2FleetPrototype.

        The name of the fleet.  # noqa: E501

        :param name: The name of this V2FleetPrototype.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def network_placements(self):
        """Gets the network_placements of this V2FleetPrototype.  # noqa: E501

        List of network locations determining in which network the workers and processed workload will be running.  # noqa: E501

        :return: The network_placements of this V2FleetPrototype.  # noqa: E501
        :rtype: list[V2NetworkPlacementPrototype]
        """
        return self._network_placements

    @network_placements.setter
    def network_placements(self, network_placements):
        """Sets the network_placements of this V2FleetPrototype.

        List of network locations determining in which network the workers and processed workload will be running.  # noqa: E501

        :param network_placements: The network_placements of this V2FleetPrototype.  # noqa: E501
        :type: list[V2NetworkPlacementPrototype]
        """
        if network_placements is None:
            raise ValueError("Invalid value for `network_placements`, must not be `None`")  # noqa: E501

        self._network_placements = network_placements

    @property
    def run_arguments(self):
        """Gets the run_arguments of this V2FleetPrototype.  # noqa: E501

        Optional arguments for the fleet that are passed to start the container.  # noqa: E501

        :return: The run_arguments of this V2FleetPrototype.  # noqa: E501
        :rtype: list[str]
        """
        return self._run_arguments

    @run_arguments.setter
    def run_arguments(self, run_arguments):
        """Sets the run_arguments of this V2FleetPrototype.

        Optional arguments for the fleet that are passed to start the container.  # noqa: E501

        :param run_arguments: The run_arguments of this V2FleetPrototype.  # noqa: E501
        :type: list[str]
        """

        self._run_arguments = run_arguments

    @property
    def run_commands(self):
        """Gets the run_commands of this V2FleetPrototype.  # noqa: E501

        Optional commands for the fleet that are passed to start the container.  # noqa: E501

        :return: The run_commands of this V2FleetPrototype.  # noqa: E501
        :rtype: list[str]
        """
        return self._run_commands

    @run_commands.setter
    def run_commands(self, run_commands):
        """Sets the run_commands of this V2FleetPrototype.

        Optional commands for the fleet that are passed to start the container.  # noqa: E501

        :param run_commands: The run_commands of this V2FleetPrototype.  # noqa: E501
        :type: list[str]
        """

        self._run_commands = run_commands

    @property
    def run_env_variables(self):
        """Gets the run_env_variables of this V2FleetPrototype.  # noqa: E501

        Optional references to config maps, secrets or literal values that are exposed as environment variables within the running task process.  # noqa: E501

        :return: The run_env_variables of this V2FleetPrototype.  # noqa: E501
        :rtype: list[V2EnvVarPrototype]
        """
        return self._run_env_variables

    @run_env_variables.setter
    def run_env_variables(self, run_env_variables):
        """Sets the run_env_variables of this V2FleetPrototype.

        Optional references to config maps, secrets or literal values that are exposed as environment variables within the running task process.  # noqa: E501

        :param run_env_variables: The run_env_variables of this V2FleetPrototype.  # noqa: E501
        :type: list[V2EnvVarPrototype]
        """

        self._run_env_variables = run_env_variables

    @property
    def run_volume_mounts(self):
        """Gets the run_volume_mounts of this V2FleetPrototype.  # noqa: E501

        Optional mounts of persistent data stores.  # noqa: E501

        :return: The run_volume_mounts of this V2FleetPrototype.  # noqa: E501
        :rtype: list[V2FleetVolumeMountPrototype]
        """
        return self._run_volume_mounts

    @run_volume_mounts.setter
    def run_volume_mounts(self, run_volume_mounts):
        """Sets the run_volume_mounts of this V2FleetPrototype.

        Optional mounts of persistent data stores.  # noqa: E501

        :param run_volume_mounts: The run_volume_mounts of this V2FleetPrototype.  # noqa: E501
        :type: list[V2FleetVolumeMountPrototype]
        """

        self._run_volume_mounts = run_volume_mounts

    @property
    def scale_cpu_limit(self):
        """Gets the scale_cpu_limit of this V2FleetPrototype.  # noqa: E501

        Number of CPU set for each task in the fleet.  # noqa: E501

        :return: The scale_cpu_limit of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._scale_cpu_limit

    @scale_cpu_limit.setter
    def scale_cpu_limit(self, scale_cpu_limit):
        """Sets the scale_cpu_limit of this V2FleetPrototype.

        Number of CPU set for each task in the fleet.  # noqa: E501

        :param scale_cpu_limit: The scale_cpu_limit of this V2FleetPrototype.  # noqa: E501
        :type: str
        """
        if scale_cpu_limit is None:
            raise ValueError("Invalid value for `scale_cpu_limit`, must not be `None`")  # noqa: E501

        self._scale_cpu_limit = scale_cpu_limit

    @property
    def scale_gpu(self):
        """Gets the scale_gpu of this V2FleetPrototype.  # noqa: E501


        :return: The scale_gpu of this V2FleetPrototype.  # noqa: E501
        :rtype: V2GPUScalePrototype
        """
        return self._scale_gpu

    @scale_gpu.setter
    def scale_gpu(self, scale_gpu):
        """Sets the scale_gpu of this V2FleetPrototype.


        :param scale_gpu: The scale_gpu of this V2FleetPrototype.  # noqa: E501
        :type: V2GPUScalePrototype
        """

        self._scale_gpu = scale_gpu

    @property
    def scale_max_execution_time(self):
        """Gets the scale_max_execution_time of this V2FleetPrototype.  # noqa: E501

        Optional maximum execution time of each attempt to process a task instance.  # noqa: E501

        :return: The scale_max_execution_time of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._scale_max_execution_time

    @scale_max_execution_time.setter
    def scale_max_execution_time(self, scale_max_execution_time):
        """Sets the scale_max_execution_time of this V2FleetPrototype.

        Optional maximum execution time of each attempt to process a task instance.  # noqa: E501

        :param scale_max_execution_time: The scale_max_execution_time of this V2FleetPrototype.  # noqa: E501
        :type: str
        """

        self._scale_max_execution_time = scale_max_execution_time

    @property
    def scale_max_instances(self):
        """Gets the scale_max_instances of this V2FleetPrototype.  # noqa: E501

        Optional maximum number of instances for this fleet, determining how many task are processed simultaneously.  # noqa: E501

        :return: The scale_max_instances of this V2FleetPrototype.  # noqa: E501
        :rtype: int
        """
        return self._scale_max_instances

    @scale_max_instances.setter
    def scale_max_instances(self, scale_max_instances):
        """Sets the scale_max_instances of this V2FleetPrototype.

        Optional maximum number of instances for this fleet, determining how many task are processed simultaneously.  # noqa: E501

        :param scale_max_instances: The scale_max_instances of this V2FleetPrototype.  # noqa: E501
        :type: int
        """
        if scale_max_instances is None:
            raise ValueError("Invalid value for `scale_max_instances`, must not be `None`")  # noqa: E501

        self._scale_max_instances = scale_max_instances

    @property
    def scale_memory_limit(self):
        """Gets the scale_memory_limit of this V2FleetPrototype.  # noqa: E501

        Amount of memory set for the instance of the fleet.  # noqa: E501

        :return: The scale_memory_limit of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._scale_memory_limit

    @scale_memory_limit.setter
    def scale_memory_limit(self, scale_memory_limit):
        """Sets the scale_memory_limit of this V2FleetPrototype.

        Amount of memory set for the instance of the fleet.  # noqa: E501

        :param scale_memory_limit: The scale_memory_limit of this V2FleetPrototype.  # noqa: E501
        :type: str
        """
        if scale_memory_limit is None:
            raise ValueError("Invalid value for `scale_memory_limit`, must not be `None`")  # noqa: E501

        self._scale_memory_limit = scale_memory_limit

    @property
    def scale_preferred_worker_profile(self):
        """Gets the scale_preferred_worker_profile of this V2FleetPrototype.  # noqa: E501

        Optional worker profile name that will be used to provision a worker. The fleet will fail if the profile is not available in the zones that are referenced as part of `connections`.  # noqa: E501

        :return: The scale_preferred_worker_profile of this V2FleetPrototype.  # noqa: E501
        :rtype: str
        """
        return self._scale_preferred_worker_profile

    @scale_preferred_worker_profile.setter
    def scale_preferred_worker_profile(self, scale_preferred_worker_profile):
        """Sets the scale_preferred_worker_profile of this V2FleetPrototype.

        Optional worker profile name that will be used to provision a worker. The fleet will fail if the profile is not available in the zones that are referenced as part of `connections`.  # noqa: E501

        :param scale_preferred_worker_profile: The scale_preferred_worker_profile of this V2FleetPrototype.  # noqa: E501
        :type: str
        """

        self._scale_preferred_worker_profile = scale_preferred_worker_profile

    @property
    def scale_retry_limit(self):
        """Gets the scale_retry_limit of this V2FleetPrototype.  # noqa: E501

        Optional number of times to rerun an instance of the task before the task is marked as failed.  # noqa: E501

        :return: The scale_retry_limit of this V2FleetPrototype.  # noqa: E501
        :rtype: int
        """
        return self._scale_retry_limit

    @scale_retry_limit.setter
    def scale_retry_limit(self, scale_retry_limit):
        """Sets the scale_retry_limit of this V2FleetPrototype.

        Optional number of times to rerun an instance of the task before the task is marked as failed.  # noqa: E501

        :param scale_retry_limit: The scale_retry_limit of this V2FleetPrototype.  # noqa: E501
        :type: int
        """

        self._scale_retry_limit = scale_retry_limit

    @property
    def tasks_specification(self):
        """Gets the tasks_specification of this V2FleetPrototype.  # noqa: E501


        :return: The tasks_specification of this V2FleetPrototype.  # noqa: E501
        :rtype: V2TasksSpecificationPrototype
        """
        return self._tasks_specification

    @tasks_specification.setter
    def tasks_specification(self, tasks_specification):
        """Sets the tasks_specification of this V2FleetPrototype.


        :param tasks_specification: The tasks_specification of this V2FleetPrototype.  # noqa: E501
        :type: V2TasksSpecificationPrototype
        """
        if tasks_specification is None:
            raise ValueError("Invalid value for `tasks_specification`, must not be `None`")  # noqa: E501

        self._tasks_specification = tasks_specification

    @property
    def tasks_state_store(self):
        """Gets the tasks_state_store of this V2FleetPrototype.  # noqa: E501


        :return: The tasks_state_store of this V2FleetPrototype.  # noqa: E501
        :rtype: V2TaskStateStorePrototype
        """
        return self._tasks_state_store

    @tasks_state_store.setter
    def tasks_state_store(self, tasks_state_store):
        """Sets the tasks_state_store of this V2FleetPrototype.


        :param tasks_state_store: The tasks_state_store of this V2FleetPrototype.  # noqa: E501
        :type: V2TaskStateStorePrototype
        """
        if tasks_state_store is None:
            raise ValueError("Invalid value for `tasks_state_store`, must not be `None`")  # noqa: E501

        self._tasks_state_store = tasks_state_store

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2FleetPrototype, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2FleetPrototype):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
