# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2TasksSpecification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "cos_bucket": "V2CosBucket",
        "indices": "str",
        "json_reference": "V2JsonReference",
    }

    attribute_map = {
        "cos_bucket": "cos_bucket",
        "indices": "indices",
        "json_reference": "json_reference",
    }

    def __init__(self, cos_bucket=None, indices=None, json_reference=None):  # noqa: E501
        """V2TasksSpecification - a model defined in Swagger"""  # noqa: E501
        self._cos_bucket = None
        self._indices = None
        self._json_reference = None
        self.discriminator = None
        if cos_bucket is not None:
            self.cos_bucket = cos_bucket
        if indices is not None:
            self.indices = indices
        if json_reference is not None:
            self.json_reference = json_reference

    @property
    def cos_bucket(self):
        """Gets the cos_bucket of this V2TasksSpecification.  # noqa: E501


        :return: The cos_bucket of this V2TasksSpecification.  # noqa: E501
        :rtype: V2CosBucket
        """
        return self._cos_bucket

    @cos_bucket.setter
    def cos_bucket(self, cos_bucket):
        """Sets the cos_bucket of this V2TasksSpecification.


        :param cos_bucket: The cos_bucket of this V2TasksSpecification.  # noqa: E501
        :type: V2CosBucket
        """

        self._cos_bucket = cos_bucket

    @property
    def indices(self):
        """Gets the indices of this V2TasksSpecification.  # noqa: E501

        Input for tasks based on predetermined indices.  # noqa: E501

        :return: The indices of this V2TasksSpecification.  # noqa: E501
        :rtype: str
        """
        return self._indices

    @indices.setter
    def indices(self, indices):
        """Sets the indices of this V2TasksSpecification.

        Input for tasks based on predetermined indices.  # noqa: E501

        :param indices: The indices of this V2TasksSpecification.  # noqa: E501
        :type: str
        """

        self._indices = indices

    @property
    def json_reference(self):
        """Gets the json_reference of this V2TasksSpecification.  # noqa: E501


        :return: The json_reference of this V2TasksSpecification.  # noqa: E501
        :rtype: V2JsonReference
        """
        return self._json_reference

    @json_reference.setter
    def json_reference(self, json_reference):
        """Sets the json_reference of this V2TasksSpecification.


        :param json_reference: The json_reference of this V2TasksSpecification.  # noqa: E501
        :type: V2JsonReference
        """

        self._json_reference = json_reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: ((item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2TasksSpecification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2TasksSpecification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
