# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2TaskProgress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "canceled": "int",
        "failed": "int",
        "pending": "int",
        "running": "int",
        "successful": "int",
    }

    attribute_map = {
        "canceled": "canceled",
        "failed": "failed",
        "pending": "pending",
        "running": "running",
        "successful": "successful",
    }

    def __init__(self, canceled=None, failed=None, pending=None, running=None, successful=None):  # noqa: E501
        """V2TaskProgress - a model defined in Swagger"""  # noqa: E501
        self._canceled = None
        self._failed = None
        self._pending = None
        self._running = None
        self._successful = None
        self.discriminator = None
        self.canceled = canceled
        self.failed = failed
        self.pending = pending
        self.running = running
        self.successful = successful

    @property
    def canceled(self):
        """Gets the canceled of this V2TaskProgress.  # noqa: E501

        The number of failed canceled in the fleet.  # noqa: E501

        :return: The canceled of this V2TaskProgress.  # noqa: E501
        :rtype: int
        """
        return self._canceled

    @canceled.setter
    def canceled(self, canceled):
        """Sets the canceled of this V2TaskProgress.

        The number of failed canceled in the fleet.  # noqa: E501

        :param canceled: The canceled of this V2TaskProgress.  # noqa: E501
        :type: int
        """
        if canceled is None:
            raise ValueError("Invalid value for `canceled`, must not be `None`")  # noqa: E501

        self._canceled = canceled

    @property
    def failed(self):
        """Gets the failed of this V2TaskProgress.  # noqa: E501

        The number of failed tasks in the fleet.  # noqa: E501

        :return: The failed of this V2TaskProgress.  # noqa: E501
        :rtype: int
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this V2TaskProgress.

        The number of failed tasks in the fleet.  # noqa: E501

        :param failed: The failed of this V2TaskProgress.  # noqa: E501
        :type: int
        """
        if failed is None:
            raise ValueError("Invalid value for `failed`, must not be `None`")  # noqa: E501

        self._failed = failed

    @property
    def pending(self):
        """Gets the pending of this V2TaskProgress.  # noqa: E501

        The number of pending tasks in the fleet.  # noqa: E501

        :return: The pending of this V2TaskProgress.  # noqa: E501
        :rtype: int
        """
        return self._pending

    @pending.setter
    def pending(self, pending):
        """Sets the pending of this V2TaskProgress.

        The number of pending tasks in the fleet.  # noqa: E501

        :param pending: The pending of this V2TaskProgress.  # noqa: E501
        :type: int
        """
        if pending is None:
            raise ValueError("Invalid value for `pending`, must not be `None`")  # noqa: E501

        self._pending = pending

    @property
    def running(self):
        """Gets the running of this V2TaskProgress.  # noqa: E501

        The number of running tasks in the fleet.  # noqa: E501

        :return: The running of this V2TaskProgress.  # noqa: E501
        :rtype: int
        """
        return self._running

    @running.setter
    def running(self, running):
        """Sets the running of this V2TaskProgress.

        The number of running tasks in the fleet.  # noqa: E501

        :param running: The running of this V2TaskProgress.  # noqa: E501
        :type: int
        """
        if running is None:
            raise ValueError("Invalid value for `running`, must not be `None`")  # noqa: E501

        self._running = running

    @property
    def successful(self):
        """Gets the successful of this V2TaskProgress.  # noqa: E501

        The number of successful tasks in the fleet.  # noqa: E501

        :return: The successful of this V2TaskProgress.  # noqa: E501
        :rtype: int
        """
        return self._successful

    @successful.setter
    def successful(self, successful):
        """Sets the successful of this V2TaskProgress.

        The number of successful tasks in the fleet.  # noqa: E501

        :param successful: The successful of this V2TaskProgress.  # noqa: E501
        :type: int
        """
        if successful is None:
            raise ValueError("Invalid value for `successful`, must not be `None`")  # noqa: E501

        self._successful = successful

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: ((item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2TaskProgress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2TaskProgress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
