# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2TaskStateStore(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"persistent_data_store": "str", "sub_path": "str"}

    attribute_map = {"persistent_data_store": "persistent_data_store", "sub_path": "sub_path"}

    def __init__(self, persistent_data_store=None, sub_path=None):  # noqa: E501
        """V2TaskStateStore - a model defined in Swagger"""  # noqa: E501
        self._persistent_data_store = None
        self._sub_path = None
        self.discriminator = None
        self.persistent_data_store = persistent_data_store
        if sub_path is not None:
            self.sub_path = sub_path

    @property
    def persistent_data_store(self):
        """Gets the persistent_data_store of this V2TaskStateStore.  # noqa: E501

        Name of referenced persistent data store resource.  # noqa: E501

        :return: The persistent_data_store of this V2TaskStateStore.  # noqa: E501
        :rtype: str
        """
        return self._persistent_data_store

    @persistent_data_store.setter
    def persistent_data_store(self, persistent_data_store):
        """Sets the persistent_data_store of this V2TaskStateStore.

        Name of referenced persistent data store resource.  # noqa: E501

        :param persistent_data_store: The persistent_data_store of this V2TaskStateStore.  # noqa: E501
        :type: str
        """
        if persistent_data_store is None:
            raise ValueError(
                "Invalid value for `persistent_data_store`, must not be `None`"
            )  # noqa: E501

        self._persistent_data_store = persistent_data_store

    @property
    def sub_path(self):
        """Gets the sub_path of this V2TaskStateStore.  # noqa: E501

        Optional object storage prefix to be used as an entry point.  # noqa: E501

        :return: The sub_path of this V2TaskStateStore.  # noqa: E501
        :rtype: str
        """
        return self._sub_path

    @sub_path.setter
    def sub_path(self, sub_path):
        """Sets the sub_path of this V2TaskStateStore.

        Optional object storage prefix to be used as an entry point.  # noqa: E501

        :param sub_path: The sub_path of this V2TaskStateStore.  # noqa: E501
        :type: str
        """

        self._sub_path = sub_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2TaskStateStore, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2TaskStateStore):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
