# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2WorkerProfileList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"worker_profiles": "list[V2WorkerProfile]"}

    attribute_map = {"worker_profiles": "worker_profiles"}

    def __init__(self, worker_profiles=None):  # noqa: E501
        """V2WorkerProfileList - a model defined in Swagger"""  # noqa: E501
        self._worker_profiles = None
        self.discriminator = None
        if worker_profiles is not None:
            self.worker_profiles = worker_profiles

    @property
    def worker_profiles(self):
        """Gets the worker_profiles of this V2WorkerProfileList.  # noqa: E501


        :return: The worker_profiles of this V2WorkerProfileList.  # noqa: E501
        :rtype: list[V2WorkerProfile]
        """
        return self._worker_profiles

    @worker_profiles.setter
    def worker_profiles(self, worker_profiles):
        """Sets the worker_profiles of this V2WorkerProfileList.


        :param worker_profiles: The worker_profiles of this V2WorkerProfileList.  # noqa: E501
        :type: list[V2WorkerProfile]
        """

        self._worker_profiles = worker_profiles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2WorkerProfileList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2WorkerProfileList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
