# coding: utf-8

"""
    Code Engine

    REST API for Code Engine  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2WorkerStatusDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'image_version': 'str',
        'profile': 'str',
        'subnet_crn': 'str',
        'zone': 'str'
    }

    attribute_map = {
        'address': 'address',
        'image_version': 'image_version',
        'profile': 'profile',
        'subnet_crn': 'subnet_crn',
        'zone': 'zone'
    }

    def __init__(self, address=None, image_version=None, profile=None, subnet_crn=None, zone=None):  # noqa: E501
        """V2WorkerStatusDetails - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._image_version = None
        self._profile = None
        self._subnet_crn = None
        self._zone = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if image_version is not None:
            self.image_version = image_version
        self.profile = profile
        self.subnet_crn = subnet_crn
        self.zone = zone

    @property
    def address(self):
        """Gets the address of this V2WorkerStatusDetails.  # noqa: E501

        Address at which the worker is accessible.  # noqa: E501

        :return: The address of this V2WorkerStatusDetails.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this V2WorkerStatusDetails.

        Address at which the worker is accessible.  # noqa: E501

        :param address: The address of this V2WorkerStatusDetails.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def image_version(self):
        """Gets the image_version of this V2WorkerStatusDetails.  # noqa: E501

        Version of the VSI base image used for this worker  # noqa: E501

        :return: The image_version of this V2WorkerStatusDetails.  # noqa: E501
        :rtype: str
        """
        return self._image_version

    @image_version.setter
    def image_version(self, image_version):
        """Sets the image_version of this V2WorkerStatusDetails.

        Version of the VSI base image used for this worker  # noqa: E501

        :param image_version: The image_version of this V2WorkerStatusDetails.  # noqa: E501
        :type: str
        """

        self._image_version = image_version

    @property
    def profile(self):
        """Gets the profile of this V2WorkerStatusDetails.  # noqa: E501

        The type of the fleet worker.  # noqa: E501

        :return: The profile of this V2WorkerStatusDetails.  # noqa: E501
        :rtype: str
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this V2WorkerStatusDetails.

        The type of the fleet worker.  # noqa: E501

        :param profile: The profile of this V2WorkerStatusDetails.  # noqa: E501
        :type: str
        """
        if profile is None:
            raise ValueError("Invalid value for `profile`, must not be `None`")  # noqa: E501

        self._profile = profile

    @property
    def subnet_crn(self):
        """Gets the subnet_crn of this V2WorkerStatusDetails.  # noqa: E501

        The CRN of the subnet the worker is connecting to.  # noqa: E501

        :return: The subnet_crn of this V2WorkerStatusDetails.  # noqa: E501
        :rtype: str
        """
        return self._subnet_crn

    @subnet_crn.setter
    def subnet_crn(self, subnet_crn):
        """Sets the subnet_crn of this V2WorkerStatusDetails.

        The CRN of the subnet the worker is connecting to.  # noqa: E501

        :param subnet_crn: The subnet_crn of this V2WorkerStatusDetails.  # noqa: E501
        :type: str
        """
        if subnet_crn is None:
            raise ValueError("Invalid value for `subnet_crn`, must not be `None`")  # noqa: E501

        self._subnet_crn = subnet_crn

    @property
    def zone(self):
        """Gets the zone of this V2WorkerStatusDetails.  # noqa: E501

        Availability zone the fleet worker is located in.  # noqa: E501

        :return: The zone of this V2WorkerStatusDetails.  # noqa: E501
        :rtype: str
        """
        return self._zone

    @zone.setter
    def zone(self, zone):
        """Sets the zone of this V2WorkerStatusDetails.

        Availability zone the fleet worker is located in.  # noqa: E501

        :param zone: The zone of this V2WorkerStatusDetails.  # noqa: E501
        :type: str
        """
        if zone is None:
            raise ValueError("Invalid value for `zone`, must not be `None`")  # noqa: E501

        self._zone = zone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2WorkerStatusDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2WorkerStatusDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
