# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2WorkerList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "first": "PaginationListFirstMetadata",
        "limit": "int",
        "next": "PaginationListNextMetadata",
        "workers": "list[V2Worker]",
    }

    attribute_map = {"first": "first", "limit": "limit", "next": "next", "workers": "workers"}

    def __init__(self, first=None, limit=50, next=None, workers=None):  # noqa: E501
        """V2WorkerList - a model defined in Swagger"""  # noqa: E501
        self._first = None
        self._limit = None
        self._next = None
        self._workers = None
        self.discriminator = None
        if first is not None:
            self.first = first
        self.limit = limit
        if next is not None:
            self.next = next
        if workers is not None:
            self.workers = workers

    @property
    def first(self):
        """Gets the first of this V2WorkerList.  # noqa: E501


        :return: The first of this V2WorkerList.  # noqa: E501
        :rtype: PaginationListFirstMetadata
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this V2WorkerList.


        :param first: The first of this V2WorkerList.  # noqa: E501
        :type: PaginationListFirstMetadata
        """

        self._first = first

    @property
    def limit(self):
        """Gets the limit of this V2WorkerList.  # noqa: E501

        Maximum number of resources per page.  # noqa: E501

        :return: The limit of this V2WorkerList.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this V2WorkerList.

        Maximum number of resources per page.  # noqa: E501

        :param limit: The limit of this V2WorkerList.  # noqa: E501
        :type: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def next(self):
        """Gets the next of this V2WorkerList.  # noqa: E501


        :return: The next of this V2WorkerList.  # noqa: E501
        :rtype: PaginationListNextMetadata
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this V2WorkerList.


        :param next: The next of this V2WorkerList.  # noqa: E501
        :type: PaginationListNextMetadata
        """

        self._next = next

    @property
    def workers(self):
        """Gets the workers of this V2WorkerList.  # noqa: E501

        Collection of fleet workers.  # noqa: E501

        :return: The workers of this V2WorkerList.  # noqa: E501
        :rtype: list[V2Worker]
        """
        return self._workers

    @workers.setter
    def workers(self, workers):
        """Sets the workers of this V2WorkerList.

        Collection of fleet workers.  # noqa: E501

        :param workers: The workers of this V2WorkerList.  # noqa: E501
        :type: list[V2Worker]
        """

        self._workers = workers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2WorkerList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2WorkerList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
