# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# coding: utf-8

"""
Code Engine

REST API for Code Engine  # noqa: E501

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2Worker(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "created_at": "datetime",
        "finished_at": "datetime",
        "fleet_id": "str",
        "href": "str",
        "id": "str",
        "name": "str",
        "project_id": "str",
        "region": "str",
        "resource_type": "str",
        "status": "str",
        "status_details": "V2WorkerStatusDetails",
    }

    attribute_map = {
        "created_at": "created_at",
        "finished_at": "finished_at",
        "fleet_id": "fleet_id",
        "href": "href",
        "id": "id",
        "name": "name",
        "project_id": "project_id",
        "region": "region",
        "resource_type": "resource_type",
        "status": "status",
        "status_details": "status_details",
    }

    def __init__(
        self,
        created_at=None,
        finished_at=None,
        fleet_id=None,
        href=None,
        id=None,
        name=None,
        project_id=None,
        region=None,
        resource_type=None,
        status=None,
        status_details=None,
    ):  # noqa: E501
        """V2Worker - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._finished_at = None
        self._fleet_id = None
        self._href = None
        self._id = None
        self._name = None
        self._project_id = None
        self._region = None
        self._resource_type = None
        self._status = None
        self._status_details = None
        self.discriminator = None
        if created_at is not None:
            self.created_at = created_at
        if finished_at is not None:
            self.finished_at = finished_at
        self.fleet_id = fleet_id
        self.href = href
        self.id = id
        self.name = name
        self.project_id = project_id
        self.region = region
        self.resource_type = resource_type
        self.status = status
        self.status_details = status_details

    @property
    def created_at(self):
        """Gets the created_at of this V2Worker.  # noqa: E501

        The timestamp when the resource was created.  # noqa: E501

        :return: The created_at of this V2Worker.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this V2Worker.

        The timestamp when the resource was created.  # noqa: E501

        :param created_at: The created_at of this V2Worker.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def finished_at(self):
        """Gets the finished_at of this V2Worker.  # noqa: E501

        The timestamp when the worker finished.  # noqa: E501

        :return: The finished_at of this V2Worker.  # noqa: E501
        :rtype: datetime
        """
        return self._finished_at

    @finished_at.setter
    def finished_at(self, finished_at):
        """Sets the finished_at of this V2Worker.

        The timestamp when the worker finished.  # noqa: E501

        :param finished_at: The finished_at of this V2Worker.  # noqa: E501
        :type: datetime
        """

        self._finished_at = finished_at

    @property
    def fleet_id(self):
        """Gets the fleet_id of this V2Worker.  # noqa: E501

        The ID of the fleet as part of which the worker is processing tasks.  # noqa: E501

        :return: The fleet_id of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._fleet_id

    @fleet_id.setter
    def fleet_id(self, fleet_id):
        """Sets the fleet_id of this V2Worker.

        The ID of the fleet as part of which the worker is processing tasks.  # noqa: E501

        :param fleet_id: The fleet_id of this V2Worker.  # noqa: E501
        :type: str
        """
        if fleet_id is None:
            raise ValueError("Invalid value for `fleet_id`, must not be `None`")  # noqa: E501

        self._fleet_id = fleet_id

    @property
    def href(self):
        """Gets the href of this V2Worker.  # noqa: E501

        URL identifying the location of the worker.  # noqa: E501

        :return: The href of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V2Worker.

        URL identifying the location of the worker.  # noqa: E501

        :param href: The href of this V2Worker.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def id(self):
        """Gets the id of this V2Worker.  # noqa: E501

        The identifier of the resource.  # noqa: E501

        :return: The id of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2Worker.

        The identifier of the resource.  # noqa: E501

        :param id: The id of this V2Worker.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this V2Worker.  # noqa: E501

        The name of the worker.  # noqa: E501

        :return: The name of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2Worker.

        The name of the worker.  # noqa: E501

        :param name: The name of this V2Worker.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this V2Worker.  # noqa: E501

        The ID of the project in which the resource is located.  # noqa: E501

        :return: The project_id of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this V2Worker.

        The ID of the project in which the resource is located.  # noqa: E501

        :param project_id: The project_id of this V2Worker.  # noqa: E501
        :type: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def region(self):
        """Gets the region of this V2Worker.  # noqa: E501

        The region of the project the resource is located in. Possible values: 'au-syd', 'br-sao', 'ca-tor', 'eu-de', 'eu-gb', 'jp-osa', 'jp-tok', 'us-east', 'us-south'.  # noqa: E501

        :return: The region of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this V2Worker.

        The region of the project the resource is located in. Possible values: 'au-syd', 'br-sao', 'ca-tor', 'eu-de', 'eu-gb', 'jp-osa', 'jp-tok', 'us-east', 'us-south'.  # noqa: E501

        :param region: The region of this V2Worker.  # noqa: E501
        :type: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def resource_type(self):
        """Gets the resource_type of this V2Worker.  # noqa: E501

        The type of the fleet worker.  # noqa: E501

        :return: The resource_type of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this V2Worker.

        The type of the fleet worker.  # noqa: E501

        :param resource_type: The resource_type of this V2Worker.  # noqa: E501
        :type: str
        """
        if resource_type is None:
            raise ValueError("Invalid value for `resource_type`, must not be `None`")  # noqa: E501
        allowed_values = ["fleet_worker_v2"]  # noqa: E501
        if resource_type not in allowed_values:
            raise ValueError(
                "Invalid value for `resource_type` ({0}), must be one of {1}".format(  # noqa: E501
                    resource_type, allowed_values
                )
            )

        self._resource_type = resource_type

    @property
    def status(self):
        """Gets the status of this V2Worker.  # noqa: E501

        Current status of the fleet worker.  # noqa: E501

        :return: The status of this V2Worker.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V2Worker.

        Current status of the fleet worker.  # noqa: E501

        :param status: The status of this V2Worker.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = [
            "pending",
            "initializing",
            "running",
            "stopping",
            "stopped",
            "failed",
            "deleting",
        ]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}".format(status, allowed_values)  # noqa: E501
            )

        self._status = status

    @property
    def status_details(self):
        """Gets the status_details of this V2Worker.  # noqa: E501


        :return: The status_details of this V2Worker.  # noqa: E501
        :rtype: V2WorkerStatusDetails
        """
        return self._status_details

    @status_details.setter
    def status_details(self, status_details):
        """Sets the status_details of this V2Worker.


        :param status_details: The status_details of this V2Worker.  # noqa: E501
        :type: V2WorkerStatusDetails
        """
        if status_details is None:
            raise ValueError("Invalid value for `status_details`, must not be `None`")  # noqa: E501

        self._status_details = status_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V2Worker, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2Worker):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
