name: Build the containers

on:
  pull_request:
  merge_group:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build-containers:
    name: Test build containers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # keep running if one leg fails
      matrix:
        dockerfile:
          - ray-node/Dockerfile
          - gateway/Dockerfile
        python:
          - "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup buildx
        uses: docker/setup-buildx-action@v4
      - name: Build ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          load: true
          tags: image:test
      - name: Inspect
        run: |
          docker image inspect image:test
